//! H-only dependency core of public submission 402's uniform H derivative.
//! Generated by make-round4-hcore.py; reachable functions and constants are copied verbatim.

pub fn parse(input: &[u8], out: &mut [u32]) -> usize {
    h_parse_mode(input, out, 0)
}

pub const H_BTD: usize = 32;

pub const H_BTDS: usize = 16;

pub const H_SMALLN: usize = 65536;

pub const H_SKS: usize = 0;

pub const H_H3BITS: u32 = 17;

pub const H_H3SIZE: usize = 131072;

pub const H_NICE: usize = 258;

pub const H_SKIPL: usize = 258;

pub const H_INH: usize = 1;

pub const H_LZK: usize = 0;

pub const H_INS: usize = 1;

pub const H_H3CAP: usize = 8;

pub const H_INSCAP: usize = 128;

pub const H_INSEND: usize = 0;

pub const H_ITERS: usize = 8;

pub const H_MINIT: usize = 1;

pub const H_ESH: u32 = 10;

pub const H_GAINK: u64 = 4;

pub const H_MBIAS: u32 = 0;

pub const H_RING: usize = 512;

pub const H_HBITS: u32 = 16;

pub const H_HSIZE: usize = 65536;

pub const H_TB: usize = 548;

pub const H_FB: usize = 320;

pub const H_BT: usize = 16384;

pub const H_SC: u32 = 16;

pub const H_UNUSED: u32 = 12;

pub const H_EW: u32 = 2;

pub const H_CHW: usize = 8;

pub const H_CHWS: usize = 16;

pub const H_DW: u32 = 0;

pub const H_OV: u32 = 3;

pub const H_DSTART: usize = 2;

pub const H_UPEN: u32 = 16;

pub const H_PM: u32 = 128;

pub const H_PUSH_LIMIT: usize = 1073741824;

pub const H_STM: usize = 1;

pub const H_STMARG: u64 = 0;

pub const H_BIG: u32 = 1048576;

pub const H_SLOTM: usize = 1;

pub const H_STARTBEST: usize = 1;

pub const H_MDEL: u32 = 24;

pub const H_RALPHA: u32 = 2;

pub const H_GK2: u64 = 2;

pub const H_F1: u64 = 8;

pub const H_CHN: usize = 65536;

pub const H_OPQ: u64 = 200;

pub const H_MDEL2: u32 = 0;

pub const H_U5: u32 = 32;

pub const H_D5: u32 = 12;

pub const H_HBPB: u64 = 40;

pub const H_LAMH: u32 = 5;

pub const H_MINH: usize = 2;

pub fn h_get(v: &[u32], i: usize) -> u32 {
    if i < v.len() {
        v[i]
    } else {
        0
    }
}

pub fn h_set(v: &mut [u32], i: usize, x: u32) {
    if i < v.len() {
        v[i] = x;
    }
}

pub fn h_bump(v: &mut [u32], i: usize, by: u32) {
    if i < v.len() {
        v[i] = v[i].wrapping_add(by);
    }
}

pub fn h_set64(v: &mut [u64], i: usize, x: u64) {
    if i < v.len() {
        v[i] = x;
    }
}

pub fn h_get8(v: &[u8], i: usize) -> u8 {
    if i < v.len() {
        v[i]
    } else {
        0
    }
}

pub fn h_byte_at(input: &[u8], i: usize) -> usize {
    if i < input.len() {
        input[i] as usize
    } else {
        0
    }
}

pub fn h_setc(a: &mut [u32; 65536], i: usize, x: u32) {
    a[i % 65536] = x;
}

pub fn h_filled(n: usize, x: u32) -> Vec<u32> {
    let mut v: Vec<u32> = Vec::with_capacity(n);
    let n8 = n / 8;
    let mut i = 0usize;
    while i < n8 {
        v.push(x);
        v.push(x);
        v.push(x);
        v.push(x);
        v.push(x);
        v.push(x);
        v.push(x);
        v.push(x);
        i += 1;
    }
    let mut j = n8 * 8;
    while j < n {
        v.push(x);
        j += 1;
    }
    v
}

pub fn h_push_guarded(v: &mut Vec<u32>, x: u32) {
    if v.len() < H_PUSH_LIMIT {
        v.push(x);
    }
}

pub fn h_sel(f: usize, a: usize, b: usize) -> usize {
    if f == 1 {
        a
    } else {
        b
    }
}

pub fn h_sel32(f: usize, a: u32, b: u32) -> u32 {
    if f == 1 {
        a
    } else {
        b
    }
}

pub fn h_sel64(f: usize, a: u64, b: u64) -> u64 {
    if f == 1 {
        a
    } else {
        b
    }
}

pub fn h_ge(a: usize, b: usize) -> usize {
    if a >= b {
        1
    } else {
        0
    }
}

pub fn h_lt(a: usize, b: usize) -> usize {
    if a < b {
        1
    } else {
        0
    }
}

pub fn h_eq(a: usize, b: usize) -> usize {
    if a == b {
        1
    } else {
        0
    }
}

pub fn h_lt32(a: u32, b: u32) -> usize {
    if a < b {
        1
    } else {
        0
    }
}

pub fn h_lt64(a: u64, b: u64) -> usize {
    if a < b {
        1
    } else {
        0
    }
}

pub fn h_umin(a: usize, b: usize) -> usize {
    if a < b {
        a
    } else {
        b
    }
}

pub fn h_umax(a: usize, b: usize) -> usize {
    if a > b {
        a
    } else {
        b
    }
}

pub fn h_eq64(a: u64, b: u64) -> usize {
    if a == b {
        1
    } else {
        0
    }
}

pub fn h_umin64(a: u64, b: u64) -> u64 {
    if a < b {
        a
    } else {
        b
    }
}

pub fn h_push_if(v: &mut Vec<u32>, f: usize, x: u32) {
    if f == 1 && v.len() < H_PUSH_LIMIT {
        v.push(x);
    }
}

pub fn h_push_m(v: &mut Vec<u32>, f: usize, len: usize, d: usize) {
    if f == 1 && v.len() < H_PUSH_LIMIT {
        v.push(h_pack_m(len, d));
    }
}

pub fn h_push_slot(mc: &mut Vec<u32>, m0: usize, f: usize, len: usize, d: usize) {
    if f == 1 {
        h_push_slot1(mc, m0, len, d);
    }
}

pub fn h_push_slot1(mc: &mut Vec<u32>, m0: usize, len: usize, d: usize) {
    let e = h_pack_m(len, d);
    let k = mc.len();
    let last = h_get(mc, k.wrapping_sub(1));
    let same = h_eq(H_SLOTM, 1) & h_lt(m0, k) & h_eq(((last / 32768) % 32) as usize, ((e / 32768) % 32) as usize);
    if same == 1 {
        h_set(mc, k.wrapping_sub(1), e);
    } else {
        h_push_guarded(mc, e);
    }
}

pub fn h_clamp_step(l: usize, room: usize) -> usize {
    if l >= 3 && l <= room {
        l
    } else {
        1
    }
}

pub fn h_clamp1(l: usize, room: usize) -> usize {
    if l >= 1 && l <= room {
        l
    } else {
        1
    }
}

pub fn h_nz64(x: u64) -> u64 {
    if x == 0 {
        1
    } else {
        x
    }
}

pub fn h_match_len(input: &[u8], a: usize, b: usize, cap: usize) -> usize {
    let mut l = 0usize;
    while l < cap && input[b + l] == input[a + l] {
        l += 1;
    }
    l
}

pub fn h_verified(input: &[u8], pos: usize, d: usize, ch: usize) -> bool {
    let n = input.len();
    if ch < 3 || ch > 258 || d < 1 || d > 32768 || d > pos || pos > n || ch > n - pos {
        return false;
    }
    let v = h_match_len(input, pos - d, pos, ch);
    v >= ch
}

pub fn h_emit_all(input: &[u8], out: &mut [u32], plan: &[u32]) -> usize {
    let n = input.len();
    let mut k = 0usize;
    let mut ntok = 0usize;
    while k < n {
        let p = h_get(plan, k) as usize;
        let ch = p / 65536;
        let d = p % 65536;
        if h_verified(input, k, d, ch) {
            out[ntok] = 16777216u32 + ((d - 1) as u32) * 256 + ((ch - 3) as u32);
            ntok += 1;
            k += ch;
        } else {
            out[ntok] = input[k] as u32;
            ntok += 1;
            k += 1;
        }
    }
    ntok
}

pub fn h_le64(input: &[u8], p: usize) -> u64 {
    let n = input.len();
    if p < n && n - p >= 8 {
        let b7 = input[p + 7] as u64;
        let lo = (input[p] as u32) | ((input[p + 1] as u32) << 8) | ((input[p + 2] as u32) << 16) | ((input[p + 3] as u32) << 24);
        let hi = (input[p + 4] as u32) | ((input[p + 5] as u32) << 8) | ((input[p + 6] as u32) << 16) | ((b7 as u32) << 24);
        (lo as u64) | ((hi as u64) << 32)
    } else {
        0
    }
}

pub fn h_first_diff(x:u64,y:u64)->usize {
    let z=x^y;
    let a=((z&0xff00ff00ff00ff00u64)>>8)|((z&0x00ff00ff00ff00ffu64)<<8);
    let b=((a&0xffff0000ffff0000u64)>>16)|((a&0x0000ffff0000ffffu64)<<16);
    let c=(b>>32)|(b<<32);
    h_umin((c.leading_zeros()/8) as usize,7)
}

pub fn h_hash4(input: &[u8], p: usize) -> usize {
    let n = input.len();
    if n >= 4 && p <= n - 4 {
        let x = (input[p] as u32) | ((input[p + 1] as u32) << 8) | ((input[p + 2] as u32) << 16) | ((input[p + 3] as u32) << 24);
        ((x.wrapping_mul(2654435761) >> (32 - H_HBITS)) as usize) % H_HSIZE
    } else {
        0
    }
}

pub fn h_hash3(input: &[u8], p: usize) -> usize {
    let n = input.len();
    if n >= 3 && p <= n - 3 {
        let x = (input[p] as u32) | ((input[p + 1] as u32) << 8) | ((input[p + 2] as u32) << 16);
        ((x.wrapping_mul(2654435761) >> (32 - H_H3BITS)) as usize) % H_H3SIZE
    } else {
        0
    }
}

pub fn h_dslot(d: usize) -> usize {
    let small = if d >= 1 { d.wrapping_sub(1) } else { 0 };
    let x = (d.wrapping_sub(1) % 65536) as u32;
    let msb = 31u32.wrapping_sub(x.leading_zeros());
    let sh = if msb >= 1 && msb <= 31 { msb.wrapping_sub(1) } else { 0 };
    let s = (2u32.wrapping_mul(msb % 32).wrapping_add((x >> (sh % 32)) & 1)) as usize;
    let big = if s > 29 { 29 } else { s };
    if d <= 4 {
        small
    } else {
        big
    }
}

pub fn h_dextra(s: usize) -> u32 {
    if s < 4 {
        0
    } else {
        ((s / 2).wrapping_sub(1)) as u32
    }
}

pub fn h_pack_m(len: usize, d: usize) -> u32 {
    let l = (len % 1024) as u32;
    let dd = if d >= 1 && d <= 32768 { d } else { 1 };
    l.wrapping_mul(1048576).wrapping_add((h_dslot(dd) as u32).wrapping_mul(32768)).wrapping_add((dd.wrapping_sub(1)) as u32)
}

pub fn h_lcode(l: usize) -> usize {
    let small = if l >= 3 { l.wrapping_sub(3) } else { 0 };
    let x = (l.wrapping_sub(3) % 1024) as u32;
    let msb = 31u32.wrapping_sub(x.leading_zeros());
    let sh = if msb >= 2 && msb <= 31 { msb.wrapping_sub(2) } else { 0 };
    let m = if msb >= 1 && msb <= 31 { msb.wrapping_sub(1) } else { 0 };
    let c = (4u32.wrapping_mul(m).wrapping_add((x >> (sh % 32)) & 3)) as usize;
    let big = if c > 28 { 28 } else { c };
    if l < 11 {
        small
    } else if l >= 258 {
        28
    } else {
        big
    }
}

pub fn h_lextra(c: usize) -> u32 {
    if c < 8 || c >= 28 {
        0
    } else {
        ((c.wrapping_sub(4)) / 4) as u32
    }
}

pub fn h_fixed_len(s: usize) -> u32 {
    if s < 144 {
        8
    } else if s < 256 {
        9
    } else if s < 280 {
        7
    } else {
        8
    }
}

pub fn h_ext_len(input: &[u8], a: usize, b: usize, from: usize, cap: usize) -> usize {
    let n = input.len();
    let bad = if a >= b || b >= n || cap > n.wrapping_sub(b) { 1usize } else { 0usize };
    let lim = if bad == 1 { 0 } else { cap };
    let mut l = from;
    let mut it = 0usize;
    while it < 300 && l < lim {
        if lim - l >= 8 {
            let x = h_le64(input, a.wrapping_add(l));
            let y = h_le64(input, b.wrapping_add(l));
            if x == y {
                l = l.wrapping_add(8);
            } else {
                l = l.wrapping_add(h_first_diff(x, y));
                break;
            }
        } else if h_byte_at(input, a.wrapping_add(l)) == h_byte_at(input, b.wrapping_add(l)) {
            l = l.wrapping_add(1);
        } else {
            break;
        }
        it += 1;
    }
    let lb = if from > cap { cap } else { from };
    let lg = if l > cap { cap } else { l };
    if bad == 1 {
        lb
    } else {
        lg
    }
}

pub fn h_ext_if(input: &[u8], f: usize, a: usize, b: usize, from: usize, cap: usize, dflt: usize) -> usize {
    if f == 1 {
        h_ext_len(input, a, b, from, cap)
    } else {
        dflt
    }
}

pub fn h_le64z(input: &[u8], p: usize) -> u64 {
    let n = input.len();
    if p < n && n - p >= 8 {
        h_le64(input, p)
    } else {
        h_le64_tail(input, p)
    }
}

pub fn h_le64_tail(input: &[u8], p: usize) -> u64 {
    let mut x = 0u64;
    let mut j = 0usize;
    while j < 8 {
        let b = h_byte_at(input, p.wrapping_add(j)) as u64;
        x = x | (b << (((j as u32).wrapping_mul(8)) % 64));
        j += 1;
    }
    x
}

pub fn h_lcp_words(input: &[u8], a: usize, b: usize, l0: usize, lim: usize) -> usize {
    let mut l = l0;
    let mut it = 0usize;
    let mut z = 0u64;
    let mut x = 0u64;
    while it < 40 && z == 0 && l < lim {
        x = h_le64z(input, a.wrapping_add(l));
        z = x ^ h_le64z(input, b.wrapping_add(l));
        l = l.wrapping_add(h_eq64(z, 0).wrapping_mul(8));
        it += 1;
    }
    let fd = h_first_diff(z, 0);
    let lf = h_sel(h_eq64(z, 0), l, l.wrapping_add(fd));
    h_umin(lf, lim).wrapping_mul(2).wrapping_add(h_byte_lt(x, x ^ z, fd))
}

pub fn h_byte_lt(x: u64, y: u64, k: usize) -> usize {
    let sh = ((k as u32).wrapping_mul(8)) % 64;
    h_lt64((x >> sh) & 255, (y >> sh) & 255)
}

pub fn h_ext_words(input: &[u8], same: usize, a: usize, b: usize, l0: usize, x: u64, y: u64, lim: usize) -> usize {
    if same == 1 {
        h_lcp_words(input, a, b, l0.wrapping_add(8), lim)
    } else {
        let fd = h_first_diff(x, y);
        l0.wrapping_add(fd).wrapping_mul(2).wrapping_add(h_byte_lt(x, y, fd))
    }
}

pub fn h_bt_walk(
    input: &[u8],
    child: &mut [u32; 65536],
    root: usize,
    pos: usize,
    cap: usize,
    best0: usize,
    rec: usize,
    maxd: usize,
    hint: usize,
    mc: &mut Vec<u32>,
    m0: usize,
) -> usize {
    let mut plt = (pos % 32768).wrapping_mul(2);
    let mut pgt = plt.wrapping_add(1);
    let mut cur = root;
    let mut ltl = 0usize;
    let mut gtl = 0usize;
    let mut len = 0usize;
    let mut best = best0;
    let mut wl = 0usize;
    let mut wd = 0usize;
    let mut depth = 0usize;
    let mut go = 1usize;
    let lim = h_sel(rec | h_lt(cap, H_INSCAP), cap, H_INSCAP);
    let stop = h_umin(lim, H_NICE);
    let kcur = hint / 512;
    let kl = h_umin(hint % 512, lim);
    while go == 1 && depth < maxd {
        let cm = cur.wrapping_sub(1);
        let dd = pos.wrapping_sub(cm);
        let bad = h_eq(cur, 0) | h_lt(pos, cur) | h_ge(dd, 32768);
        if bad == 1 {
            go = 0;
        } else {
            let l0 = h_sel(h_eq(cur, kcur) & h_lt(len, kl), kl, len);
            let x = h_le64z(input, cm.wrapping_add(l0));
            let y = h_le64z(input, pos.wrapping_add(l0));
            let same = h_eq64(x, y);
            let l2 = h_ext_words(input, same, cm, pos, l0, x, y, lim);
            len = h_umin(l2 / 2, lim);
            h_push_slot(mc, m0, rec & h_lt(best, len), len, dd);
            wd = h_sel(h_lt(wl, len), dd, wd);
            wl = h_umax(len, wl);
            best = h_umax(len, best);
            let cs = (cm % 32768).wrapping_mul(2);
            let c0 = child[cs % 65536];
            let c1 = child[cs.wrapping_add(1) % 65536];
            if len >= stop {
                h_setc(child, plt, c0);
                h_setc(child, pgt, c1);
                go = 2;
            } else {
                let sm = l2 % 2;
                h_setc(child, h_sel(sm, plt, pgt), cur as u32);
                let nx = cs.wrapping_add(sm);
                plt = h_sel(sm, nx, plt);
                pgt = h_sel(sm, pgt, nx);
                cur = h_sel(sm, c1 as usize, c0 as usize);
                ltl = h_sel(sm, len, ltl);
                gtl = h_sel(sm, gtl, len);
                len = h_umin(ltl, gtl);
            }
        }
        depth += 1;
    }
    if go != 2 {
        h_setc(child, plt, 0);
        h_setc(child, pgt, 0);
    }
    best.wrapping_add((wl % 512).wrapping_mul(512)).wrapping_add((wd % 65536).wrapping_mul(262144))
}

pub fn h_sks_rec(gap: usize) -> usize {
    let d = if H_SKS == 0 { 1 } else { H_SKS };
    h_eq(H_SKS, 0) ^ 1 & h_eq(gap % d, 0)
}

pub fn h_find_pos(
    input: &[u8],
    h4: &mut [u32; 65536],
    h3: &mut [u32; H_H3SIZE],
    child: &mut [u32; 65536],
    mc: &mut Vec<u32>,
    st: &mut [usize; 4],
    pos: usize,
    maxd: usize,
) {
    let n = input.len();
    if n < 4 || pos > n - 4 {
        return;
    }
    let skip = st[0];
    let sfrom = st[1];
    let sdist = st[2];
    let hint = st[3];
    let rem = n - pos;
    let cap = h_umin(rem, 258);
    let gap = skip.wrapping_sub(pos);
    let rec = h_ge(pos, skip) | h_lt(pos, sfrom) | h_sks_rec(gap);
    let inh = (rec ^ 1) & h_eq(H_INH, 1) & h_ge(gap, 3) & h_ge(258, gap);
    h_push_m(mc, inh, gap.wrapping_add(512), sdist);
    let x3 = h_hash3(input, pos) % H_H3SIZE;
    let c3 = h3[x3] as usize;
    h3[x3] = (pos + 1) as u32;
    let m0 = mc.len();
    let c3m = c3.wrapping_sub(1);
    let ok3 = rec & h_lt(0, c3) & h_ge(pos, c3) & h_lt(pos.wrapping_sub(c3m), 32768);
    let l3 = h_ext_if(input, ok3, c3m, pos, 0, h_umin(cap, H_H3CAP), 0);
    let f3 = h_ge(l3, 3);
    h_push_m(mc, f3, l3, pos.wrapping_sub(c3m));
    let best = h_sel(f3, l3, 2);
    let ins = rec | h_eq(H_INS, 1) | h_ge(H_INSEND, gap);
    let x4 = h_hash4(input, pos) % 65536;
    let r4 = h4[x4];
    h4[x4] = h_sel32(ins, (pos + 1) as u32, r4);
    let depth = h_sel(ins, maxd, 0);
    let bb = h_bt_walk(input, child, r4 as usize, pos, cap, best, rec, depth, hint, mc, m0);
    let b = bb % 512;
    let wl = (bb / 512) % 512;
    let bd = bb / 262144;
    let hk = h_ge(wl, 2) & h_ge(bd, 1) & h_ge(pos.wrapping_add(1), bd);
    st[3] = h_sel(hk, (pos.wrapping_add(2).wrapping_sub(bd)).wrapping_mul(512).wrapping_add(wl.wrapping_sub(1)), 0);
    let ml = mc.len();
    let ns = rec & h_ge(b, H_SKIPL) & h_lt(skip, pos.wrapping_add(b)) & h_lt(m0, ml);
    st[2] = h_sel(ns, bd, sdist);
    st[1] = h_sel(ns, pos.wrapping_add(1).wrapping_add(H_LZK), sfrom);
    st[0] = h_sel(ns, pos.wrapping_add(b), skip);
}

pub fn h_find_all(input: &[u8], mstart: &mut Vec<u32>, mc: &mut Vec<u32>, maxd: usize) {
    let n = input.len();
    let mut h4 = [0u32; 65536];
    let mut h3 = [0u32; H_H3SIZE];
    let mut child = [0u32; 65536];
    let mut st = [0usize; 4];
    st[2] = 1;
    let mut pos = 0usize;
    while pos < n {
        h_push_guarded(mstart, mc.len() as u32);
        h_find_pos(input, &mut h4, &mut h3, &mut child, mc, &mut st, pos, maxd);
        pos += 1;
    }
    h_push_guarded(mstart, mc.len() as u32);
}

pub fn h_find_spare(input: &[u8], f: usize) {
    if f == 1 {
        let mut a: Vec<u32> = Vec::new();
        let mut b: Vec<u32> = Vec::new();
        h_find_all(input, &mut a, &mut b, 1);
    }
}

pub fn h_bucket_end(l: usize) -> usize {
    if l < 11 {
        l
    } else if l >= 258 {
        258
    } else {
        let c = h_lcode(l);
        let e = h_lextra(c) % 8;
        let base = 3u32.wrapping_add(4u32.wrapping_add((c % 4) as u32) << e);
        let end = (base.wrapping_add(1u32 << e).wrapping_sub(1)) as usize;
        if end > 257 {
            257
        } else {
            end
        }
    }
}

pub fn h_build_bend(bend: &mut [u32; 512]) {
    let mut l = 0usize;
    while l < 259 {
        bend[l % 512] = h_bucket_end(l) as u32;
        l += 1;
    }
}

pub fn h_lg5(w: usize) -> usize {
    let x = (w % 64) as u32;
    let k = 31u32.wrapping_sub(x.leading_zeros()) as usize;
    if k > 4 {
        4
    } else {
        k
    }
}

pub fn h_load_ct(tbl: &[u32], toff: usize, ct: &mut [u32; 1024], lam: u32) {
    let mut x = 0usize;
    while x < 259 {
        ct[x % 1024] = h_get(tbl, toff.wrapping_add(256).wrapping_add(x)).saturating_sub(lam);
        x += 1;
    }
    let mut s = 0usize;
    while s < 30 {
        ct[(512 + s) % 1024] = h_get(tbl, toff.wrapping_add(515).wrapping_add(s));
        s += 1;
    }
    let mut c = 0usize;
    while c < 256 {
        ct[(768 + c) % 1024] = h_get(tbl, toff.wrapping_add(c)).saturating_sub(lam);
        c += 1;
    }
}

pub fn h_rm_update(rm: &mut [u64; 4096], i: usize, c: u64) {
    let s = i % H_RING;
    rm[s % 4096] = c;
    let a1 = rm[i.wrapping_add(1) % H_RING];
    let m2 = h_umin64(c, a1);
    rm[(H_RING + s) % 4096] = m2;
    let a2 = rm[(H_RING + i.wrapping_add(2) % H_RING) % 4096];
    let m4 = h_umin64(m2, a2);
    rm[(2 * H_RING + s) % 4096] = m4;
    let a4 = rm[(2 * H_RING + i.wrapping_add(4) % H_RING) % 4096];
    let m8 = h_umin64(m4, a4);
    rm[(3 * H_RING + s) % 4096] = m8;
    let a8 = rm[(3 * H_RING + i.wrapping_add(8) % H_RING) % 4096];
    let m16 = h_umin64(m8, a8);
    rm[(4 * H_RING + s) % 4096] = m16;
}

pub fn h_rm_update3(rm: &mut [u64; 4096], i: usize, c: u64) {
    let s = i % H_RING;
    rm[s % 4096] = c;
    let a1 = rm[i.wrapping_add(1) % H_RING];
    let m2 = h_umin64(c, a1);
    rm[(H_RING + s) % 4096] = m2;
    let a2 = rm[(H_RING + i.wrapping_add(2) % H_RING) % 4096];
    let m4 = h_umin64(m2, a2);
    rm[(2 * H_RING + s) % 4096] = m4;
    let a4 = rm[(2 * H_RING + i.wrapping_add(4) % H_RING) % 4096];
    let m8 = h_umin64(m4, a4);
    rm[(3 * H_RING + s) % 4096] = m8;
}

pub fn h_rm_upd(f: usize, rm: &mut [u64; 4096], i: usize, c: u64) {
    if f == 1 {
        h_rm_update(rm, i, c);
    } else {
        h_rm_update3(rm, i, c);
    }
}

pub fn h_bkt_val(rm: &[u64; 4096], ct: &[u32; 1024], i: usize, x: usize, e: usize, dcs: u64) -> u64 {
    let k = h_lg5(e.wrapping_add(1).wrapping_sub(x));
    let p = (1u32 << ((k % 8) as u32)) as usize;
    let kr = k.wrapping_mul(H_RING);
    let ra = rm[kr.wrapping_add(i.wrapping_add(x) % H_RING) % 4096];
    let rb = rm[kr.wrapping_add(i.wrapping_add(e).wrapping_add(1).wrapping_sub(p) % H_RING) % 4096];
    h_umin64(ra, rb).wrapping_add(((ct[x % 1024] as u64) << 32).wrapping_add(dcs))
}

pub fn h_query(x: usize, y: usize, k: usize, slot: usize) -> u32 {
    ((x % 512) as u32)
        .wrapping_add(((y % 512) as u32).wrapping_mul(512))
        .wrapping_add(((k % 8) as u32).wrapping_mul(262144))
        .wrapping_add(((slot % 32) as u32).wrapping_mul(2097152))
}

pub fn h_prune_short(rm: &[u64; 4096], ct: &[u32; 1024], i: usize, lo: usize, hi: usize, dcs: u64, slot: usize, best0: u64, keep: usize, items: &mut Vec<u32>) -> u64 {
    let mut best = best0;
    let mut x = lo;
    while x <= hi && x < 11 {
        let v = rm[i.wrapping_add(x) % H_RING].wrapping_add(((ct[x % 1024] as u64) << 32).wrapping_add(dcs));
        h_push_if(items, keep & (h_lt64(best.wrapping_add((H_PM as u64) << 32), v) ^ 1), h_query(x, x, 0, slot));
        best = h_umin64(v, best);
        x += 1;
    }
    best
}

pub fn h_prune_bkt(rm: &[u64; 4096], ct: &[u32; 1024], bend: &[u32; 512], i: usize, lo: usize, hi: usize, dcs: u64, slot: usize, best0: u64, keep: usize, items: &mut Vec<u32>) -> u64 {
    let mut best = best0;
    let mut x = lo;
    let mut it = 0usize;
    while it < 32 && x <= hi && x < 259 {
        let e = h_umin(h_umax(bend[x % 512] as usize, x), hi);
        let v = h_bkt_val(rm, ct, i, x, e, dcs);
        let k = h_lg5(e.wrapping_add(1).wrapping_sub(x));
        let p = (1u32 << ((k % 8) as u32)) as usize;
        let q = h_query(x, e.wrapping_add(1).wrapping_sub(p), k, slot);
        h_push_if(items, keep & (h_lt64(best.wrapping_add((H_PM as u64) << 32), v) ^ 1), q);
        best = h_umin64(v, best);
        x = e.wrapping_add(1);
        it += 1;
    }
    best
}

pub fn h_prune_pos(rm: &[u64; 4096], ct: &[u32; 1024], bend: &[u32; 512], mc: &[u32], ms: usize, me: usize, i: usize, lit: u64, chw: usize, msub: u32, keep: usize, items: &mut Vec<u32>) -> u64 {
    let ml = h_get(mc, me.wrapping_sub(1)) as usize;
    let ll0 = ml / 1048576;
    let hl = h_umin(h_sel(h_ge(ll0, 512), ll0.wrapping_sub(512), ll0), 258);
    let dl = ct[(512 + (ml / 32768) % 32) % 1024].saturating_sub(msub);
    let vl = h_bkt_val(rm, ct, i, hl, hl, (dl as u64) << 32);
    let mut best = h_sel64(h_lt(ms, me) & h_ge(hl, 3) & h_lt64(vl, lit), vl, lit);
    let mut k = ms;
    let mut lo = 3usize;
    while k < me {
        let m = h_get(mc, k) as usize;
        let len0 = m / 1048576;
        let slot = (m / 32768) % 32;
        let dcs = (ct[(512 + slot) % 1024].saturating_sub(msub) as u64) << 32;
        let flag = h_ge(len0, 512);
        let h = h_umin(h_sel(flag, len0.wrapping_sub(512), len0), 258);
        let a = h_sel(flag, h, lo);
        let b1 = h_prune_short(rm, ct, i, a, h_umin(h, 10), dcs, slot, best, keep, items);
        let a2 = h_umax(a, 11);
        let a3 = h_sel(h_lt(a2.wrapping_add(chw), h), h.wrapping_sub(chw), a2);
        best = h_prune_bkt(rm, ct, bend, i, a3, h, dcs, slot, b1, keep, items);
        lo = h_sel((flag ^ 1) & h_ge(h, lo), h.wrapping_add(1), lo);
        k += 1;
    }
    best
}

pub fn h_relax_short(rm: &[u64; 4096], ct: &[u32; 1024], i: usize, lo: usize, hi: usize, dcs: u64, best0: u64) -> u64 {
    let mut best = best0;
    let mut x = lo;
    while x <= hi && x < 11 {
        let v = rm[i.wrapping_add(x) % H_RING].wrapping_add(((ct[x % 1024] as u64) << 32).wrapping_add(dcs));
        best = h_umin64(v, best);
        x += 1;
    }
    best
}

pub fn h_relax_bkt(rm: &[u64; 4096], ct: &[u32; 1024], bend: &[u32; 512], i: usize, lo: usize, hi: usize, dcs: u64, best0: u64) -> u64 {
    let mut best = best0;
    let mut x = lo;
    let mut it = 0usize;
    while it < 32 && x <= hi && x < 259 {
        let e = h_umin(h_umax(bend[x % 512] as usize, x), hi);
        best = h_umin64(h_bkt_val(rm, ct, i, x, e, dcs), best);
        x = e.wrapping_add(1);
        it += 1;
    }
    best
}

pub fn h_relax_pos(rm: &[u64; 4096], ct: &[u32; 1024], bend: &[u32; 512], mc: &[u32], ms: usize, me: usize, i: usize, lit: u64, chw: usize, msub: u32) -> u64 {
    let mut best = lit;
    let mut k = ms;
    let mut lo = 3usize;
    while k < me {
        let m = h_get(mc, k) as usize;
        let len0 = m / 1048576;
        let dcs = (ct[(512 + (m / 32768) % 32) % 1024].saturating_sub(msub) as u64) << 32;
        let flag = h_ge(len0, 512);
        let h = h_umin(h_sel(flag, len0.wrapping_sub(512), len0), 258);
        let a = h_sel(flag, h, lo);
        let b1 = h_relax_short(rm, ct, i, a, h_umin(h, 10), dcs, best);
        let a2 = h_umax(a, 11);
        let a3 = h_sel(h_lt(a2.wrapping_add(chw), h), h.wrapping_sub(chw), a2);
        best = h_relax_bkt(rm, ct, bend, i, a3, h, dcs, b1);
        lo = h_sel((flag ^ 1) & h_ge(h, lo), h.wrapping_add(1), lo);
        k += 1;
    }
    best
}

pub fn h_prune_or_relax(rm: &[u64; 4096], ct: &[u32; 1024], bend: &[u32; 512], mc: &[u32], ms: usize, me: usize, i: usize, lit: u64, chw: usize, msub: u32, keep: usize, items: &mut Vec<u32>) -> u64 {
    if keep == 1 {
        h_prune_pos(rm, ct, bend, mc, ms, me, i, lit, chw, msub, keep, items)
    } else {
        h_relax_pos(rm, ct, bend, mc, ms, me, i, lit, chw, msub)
    }
}

pub fn h_relax_items(rm: &[u64; 4096], ct: &[u32; 1024], items: &[u32], s: usize, e: usize, i: usize, lit: u64) -> u64 {
    let mut best = lit;
    let mut t = s;
    while t < e {
        let q = h_get(items, t) as usize;
        let kr = ((q / 262144) % 8).wrapping_mul(H_RING);
        let ra = rm[kr.wrapping_add(i.wrapping_add(q) % H_RING) % 4096];
        let rb = if kr==0 {ra} else {rm[kr.wrapping_add(i.wrapping_add(q / 512) % H_RING) % 4096]};
        let c = ct[q % 512].wrapping_add(ct[(512 + (q / 2097152) % 32) % 1024]);
        let v = h_umin64(ra, rb).wrapping_add((c as u64) << 32);
        best = h_umin64(v, best);
        t += 1;
    }
    best
}

pub fn h_dp_prune(
    input: &[u8],
    rm: &mut [u64; 4096],
    ct: &[u32; 1024],
    bend: &[u32; 512],
    mstart: &[u32],
    mc: &[u32],
    choice: &mut [u32],
    chw: usize,
    msub: u32,
    keep: usize,
    items: &mut Vec<u32>,
    istart: &mut Vec<u32>,
    lo: usize,
    hi: usize,
    l4: usize,
    co: usize,
) {
    let mut i = hi;
    while i > lo {
        i -= 1;
        let lit = rm[i.wrapping_add(1) % H_RING].wrapping_add((ct[768usize.wrapping_add(h_byte_at(input, i)) % 1024] as u64) << 32);
        h_push_if(istart, keep, items.len() as u32);
        let ms = h_get(mstart, i) as usize;
        let me = h_get(mstart, i.wrapping_add(1)) as usize;
        let best = h_prune_or_relax(rm, ct, bend, mc, ms, me, i, lit, chw, msub, keep, items);
        let l = ((best as u32) as usize).wrapping_sub(i);
        h_rm_upd(l4, rm, i, (best & 0xFFFF_FFFF_0000_0000) | (i as u64));
        h_set(choice, co.wrapping_add(i), h_sel32(h_ge(l, 3) & h_ge(258, l), (l as u32).wrapping_mul(65536), 0));
    }
}

pub fn h_blk_lo(bpos: &[u32], b: usize, hi: usize) -> usize {
    h_sel(h_eq(b, 0), 0, h_umin(h_get(bpos, b) as usize, hi))
}

pub fn h_pass_prune(
    input: &[u8],
    mstart: &[u32],
    mc: &[u32],
    tbl: &[u32],
    bend: &[u32; 512],
    bpos: &[u32],
    nb: usize,
    choice: &mut [u32],
    chw: usize,
    msub: u32,
    keep: usize,
    items: &mut Vec<u32>,
    istart: &mut Vec<u32>,
    co: usize,
    lam: u32,
) {
    let n = input.len();
    let mut rm = [0u64; 4096];
    let mut ct = [0u32; 1024];
    h_rm_update(&mut rm, n, n as u64);
    let mut hi = n;
    let mut k = 0usize;
    while k < nb {
        let b = nb - 1 - k;
        let lo = h_blk_lo(bpos, b, hi);
        h_load_ct(tbl, b.wrapping_mul(H_TB), &mut ct, lam);
        h_dp_prune(input, &mut rm, &ct, bend, mstart, mc, choice, chw, msub, keep, items, istart, lo, hi, h_ge(chw, 15), co);
        hi = lo;
        k += 1;
    }
    h_push_if(istart, keep, items.len() as u32);
}

pub fn h_dp_items(input: &[u8], rm: &mut [u64; 4096], ct: &[u32; 1024], choice: &mut [u32], items: &[u32], istart: &[u32], lo: usize, hi: usize, l4: usize, co: usize) {
    let n = input.len();
    let mut e = h_get(istart, n.wrapping_sub(hi)) as usize;
    let mut i = hi;
    while i > lo {
        i -= 1;
        let lit = rm[i.wrapping_add(1) % H_RING].wrapping_add((ct[768usize.wrapping_add(h_byte_at(input, i)) % 1024] as u64) << 32);
        let s = e;
        e = h_get(istart, n.wrapping_sub(i)) as usize;
        let best = h_relax_items(rm, ct, items, s, e, i, lit);
        let l = ((best as u32) as usize).wrapping_sub(i);
        h_rm_upd(l4, rm, i, (best & 0xFFFF_FFFF_0000_0000) | (i as u64));
        h_set(choice, co.wrapping_add(i), h_sel32(h_ge(l, 3) & h_ge(258, l), (l as u32).wrapping_mul(65536), 0));
    }
}

pub fn h_pass_items(input: &[u8], tbl: &[u32], bpos: &[u32], nb: usize, choice: &mut [u32], items: &[u32], istart: &[u32], l4: usize, co: usize, lam: u32) {
    let n = input.len();
    let mut rm = [0u64; 4096];
    let mut ct = [0u32; 1024];
    h_rm_update(&mut rm, n, n as u64);
    let mut hi = n;
    let mut k = 0usize;
    while k < nb {
        let b = nb - 1 - k;
        let lo = h_blk_lo(bpos, b, hi);
        h_load_ct(tbl, b.wrapping_mul(H_TB), &mut ct, lam);
        h_dp_items(input, &mut rm, &ct, choice, items, istart, lo, hi, l4, co);
        hi = lo;
        k += 1;
    }
}

pub fn h_find_dist(mstart: &[u32], mc: &[u32], p: usize, l: usize) -> usize {
    let ms = h_get(mstart, p) as usize;
    let me = h_get(mstart, p.wrapping_add(1)) as usize;
    let mut d = 0usize;
    let mut k = ms;
    while k < me && d == 0 {
        let m = h_get(mc, k) as usize;
        let len0 = m / 1048576;
        let h = h_sel(h_ge(len0, 512), len0.wrapping_sub(512), len0);
        d = h_sel(h_ge(h, l), m % 32768 + 1, 0);
        k += 1;
    }
    d
}

pub fn h_clear(v: &mut [u32], a: usize, b: usize) {
    let mut i = a;
    while i < b {
        h_set(v, i, 0);
        i += 1;
    }
}

pub fn h_dist_of(mstart: &[u32], mc: &[u32], pos: usize, len: usize, d0: usize) -> usize {
    if len >= 3 && d0 == 0 {
        h_find_dist(mstart, mc, pos, len)
    } else {
        d0
    }
}

pub fn h_walk_bump(fr: &mut [u32], off: usize, st: usize, d: usize, b: usize) {
    if st >= 3 {
        let lc = h_lcode(st);
        let s = h_dslot(d);
        h_bump(fr, off.wrapping_add(257).wrapping_add(lc), 1);
        h_bump(fr, off.wrapping_add(288).wrapping_add(s), 1);
        h_bump(fr, off.wrapping_add(318), h_lextra(lc).wrapping_add(h_dextra(s)));
        h_bump(fr, off.wrapping_add(319), st as u32);
    } else {
        h_bump(fr, off.wrapping_add(b), 1);
        h_bump(fr, off.wrapping_add(319), 1);
    }
}

pub fn h_walk(input: &[u8], mstart: &[u32], mc: &[u32], choice: &mut [u32], co: usize, fr: &mut [u32], bpos: &mut [u32]) -> usize {
    let n = input.len();
    let mut pos = 0usize;
    let mut b = 0usize;
    let mut t = 0usize;
    h_clear(fr, 0, H_FB);
    h_set(bpos, 0, 0);
    while pos < n {
        let c = h_get(choice, co.wrapping_add(pos)) as usize;
        let len = c / 65536;
        let d0 = c % 65536;
        let d = h_dist_of(mstart, mc, pos, len, d0);
        let st0 = h_clamp_step(len, n - pos);
        let st = h_sel(h_ge(d, 1), st0, 1);
        let ism = h_ge(st, 3);
        h_set(choice, co.wrapping_add(pos), h_sel32(ism, (len as u32).wrapping_mul(65536).wrapping_add(d as u32), 0));
        h_walk_bump(fr, b.wrapping_mul(H_FB), st, d, h_byte_at(input, pos));
        let stt = h_clamp1(st, n - pos);
        pos += stt;
        t = t.wrapping_add(1);
        if t >= H_BT && pos < n {
            t = 0;
            b = b.wrapping_add(1);
            h_clear(fr, b.wrapping_mul(H_FB), b.wrapping_mul(H_FB).wrapping_add(H_FB));
            h_set(bpos, b, pos as u32);
        }
    }
    b.wrapping_add(1)
}

pub fn h_insert_sorted(order: &mut [u32], k: usize, s: usize, freq: &[u32], off: usize) {
    let fs = h_get(freq, off.wrapping_add(s));
    let mut j = k;
    while j > 0 {
        let o = h_get(order, j - 1) as usize;
        let fo = h_get(freq, off.wrapping_add(o));
        if fo <= fs {
            break;
        }
        h_set(order, j, o as u32);
        j -= 1;
    }
    h_set(order, j, s as u32);
}

pub fn h_radix_pass(freq: &[u32], off: usize, src: &[u32], dst: &mut [u32], k: usize, sh: u32) {
    let mut cnt = [0u32; 256];
    let mut i = 0usize;
    while i < k && i < 288 {
        let f = h_get(freq, off.wrapping_add(h_get(src, i) as usize));
        let dg = ((f >> (sh % 32)) % 256) as usize;
        cnt[dg] = cnt[dg].wrapping_add(1);
        i += 1;
    }
    let mut acc = 0u32;
    let mut d = 0usize;
    while d < 256 {
        let c = cnt[d];
        cnt[d] = acc;
        acc = acc.wrapping_add(c);
        d += 1;
    }
    let mut j = 0usize;
    while j < k && j < 288 {
        let s = h_get(src, j);
        let f = h_get(freq, off.wrapping_add(s as usize));
        let dg = ((f >> (sh % 32)) % 256) as usize;
        h_set(dst, cnt[dg] as usize, s);
        cnt[dg] = cnt[dg].wrapping_add(1);
        j += 1;
    }
}

pub fn h_sort_live(freq: &[u32], off: usize, nsym: usize, order: &mut [u32]) -> usize {
    let mut tmp = [0u32; 288];
    let mut k = 0usize;
    let mut big = 0usize;
    let mut s = 0usize;
    while s < nsym && s < 288 {
        let f = h_get(freq, off.wrapping_add(s));
        let old = tmp[k % 288];
        let live = h_lt32(0, f);
        tmp[k % 288] = h_sel32(live, s as u32, old);
        k = k.wrapping_add(live);
        big = big | h_lt32(65535, f);
        s += 1;
    }
    let kr = h_sel(big, 0, k);
    h_radix_pass(freq, off, &tmp, order, kr, 0);
    h_copy32(order, 0, &mut tmp, 0, kr);
    h_radix_pass(freq, off, &tmp, order, kr, 8);
    let kb = h_sel(big, k, 0);
    let mut j = 0usize;
    while j < kb && j < 288 {
        h_insert_sorted(order, j, tmp[j % 288] as usize, freq, off);
        j += 1;
    }
    k
}

pub fn h_load_w(freq: &[u32], off: usize, order: &[u32], k: usize, wa: &mut [u64]) {
    let mut i = 0usize;
    while i < k && i < 288 {
        let s = h_get(order, i) as usize;
        h_set64(wa, i, h_get(freq, off.wrapping_add(s)) as u64);
        i += 1;
    }
}

pub fn h_pm_level(lw: &[u64; 288], k: usize, w: &mut [u64; 1152], src: usize, curlen: usize, dst: usize, flags: &mut [u8; 9216], foff: usize) -> usize {
    let npk = curlen / 2;
    let total = k.wrapping_add(npk);
    let mut a = 0usize;
    let mut p = 0usize;
    let mut t = 0usize;
    while t < total && t < 576 {
        let lv = if a < k { lw[a % 288] } else { 0xFFFF_FFFF_FFFF_FFFFu64 };
        let i2 = src.wrapping_add(p.wrapping_mul(2));
        let pw = if p < npk { w[i2 % 1152].wrapping_add(w[i2.wrapping_add(1) % 1152]) } else { 0xFFFF_FFFF_FFFF_FFFFu64 };
        if lv <= pw {
            w[dst.wrapping_add(t) % 1152] = lv;
            flags[foff.wrapping_add(t) % 9216] = 1;
            a = a.wrapping_add(1);
        } else {
            w[dst.wrapping_add(t) % 1152] = pw;
            flags[foff.wrapping_add(t) % 9216] = 0;
            p = p.wrapping_add(1);
        }
        t += 1;
    }
    total
}

pub fn h_pm_levels(lw: &[u64; 288], k: usize, w: &mut [u64; 1152], flags: &mut [u8; 9216], maxbits: usize) {
    let mut curlen = k;
    let mut lev = 1usize;
    while lev < maxbits && lev < 16 {
        curlen = h_pm_level(lw, k, w, ((lev + 1) % 2).wrapping_mul(576), curlen, (lev % 2).wrapping_mul(576), flags, lev.wrapping_mul(576));
        lev += 1;
    }
}

pub fn h_count_leaves(flags: &[u8], foff: usize, s: usize) -> usize {
    let mut c = 0usize;
    let mut i = 0usize;
    while i < s && i < 576 {
        c = if h_get8(flags, foff.wrapping_add(i)) == 1 { c.wrapping_add(1) } else { c };
        i += 1;
    }
    c
}

pub fn h_inc_prefix(cnt: &mut [u32], m: usize) {
    let mut i = 0usize;
    while i < m && i < 288 {
        h_bump(cnt, i, 1);
        i += 1;
    }
}

pub fn h_count_back(flags: &[u8], cnt: &mut [u32], k: usize, maxbits: usize) -> usize {
    let mut s = if k >= 2 { k.wrapping_mul(2).wrapping_sub(2) } else { 0 };
    let mut lv = h_sel(h_ge(maxbits, 1) & h_ge(16, maxbits), maxbits.wrapping_sub(1), 0);
    while lv > 0 {
        let cl = h_count_leaves(flags, lv.wrapping_mul(576), s);
        h_inc_prefix(cnt, cl);
        s = h_sel(h_ge(s, cl), s.wrapping_sub(cl).wrapping_mul(2), 0);
        lv -= 1;
    }
    s
}

pub fn h_assign_lens(order: &[u32], cnt: &[u32], k: usize, lens: &mut [u32], loff: usize) {
    let mut r = 0usize;
    while r < k && r < 288 {
        let s2 = h_get(order, r) as usize;
        h_set(lens, loff.wrapping_add(s2), h_get(cnt, r));
        r += 1;
    }
}

pub fn h_pkg_merge_pm(freq: &[u32], off: usize, nsym: usize, maxbits: usize, lens: &mut [u32], loff: usize) {
    let mut order = [0u32; 288];
    let mut lw = [0u64; 288];
    let mut w = [0u64; 1152];
    let mut flags = [0u8; 9216];
    let mut cnt = [0u32; 288];
    h_clear(lens, loff, loff.wrapping_add(nsym));
    let k = h_sort_live(freq, off, nsym, &mut order);
    let s0 = order[0] as usize;
    let v0 = h_get(lens, loff.wrapping_add(s0));
    h_set(lens, loff.wrapping_add(s0), h_sel32(h_eq(k, 1), 1, v0));
    let kk = h_sel(h_ge(k, 2) & h_ge(15, maxbits), k, 0);
    h_load_w(freq, off, &order, kk, &mut lw);
    h_load_w(freq, off, &order, kk, &mut w);
    h_pm_levels(&lw, kk, &mut w, &mut flags, maxbits);
    let s = h_count_back(&flags, &mut cnt, kk, maxbits);
    h_inc_prefix(&mut cnt, s);
    h_assign_lens(&order, &cnt, kk, lens, loff);
}

pub const H_CL_ORDER: [usize; 19] = [16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15];

pub fn h_run_len(all: &[u32], i: usize, m: usize) -> usize {
    let v = h_get(all, i);
    let mut r = 1usize;
    while r < 1000 {
        let j = i.wrapping_add(r);
        if j >= m {
            break;
        }
        if h_get(all, j) != v {
            break;
        }
        r += 1;
    }
    r
}

pub fn h_rle_stats(all: &[u32], m: usize, clf: &mut [u32]) -> u64 {
    let mut extra = 0u64;
    let mut i = 0usize;
    while i < m {
        let v = h_get(all, i) as usize;
        let run = h_run_len(all, i, m);
        let q0 = run / 138;
        let r0 = run % 138;
        let rest = run.wrapping_sub(1);
        let q1 = rest / 6;
        let r1 = rest % 6;
        let e18 = if r0 >= 11 { 1usize } else { 0usize };
        let e16 = if r1 >= 3 { 1usize } else { 0usize };
        let add18 = if v == 0 { q0.wrapping_add(e18) } else { 0 };
        let add17 = if v == 0 && r0 >= 3 && r0 < 11 { 1usize } else { 0usize };
        let add0 = if v == 0 && r0 < 3 { r0 } else { 0 };
        let add16 = if v == 0 { 0 } else { q1.wrapping_add(e16) };
        let addv = if v == 0 { 0 } else if r1 < 3 { r1.wrapping_add(1) } else { 1 };
        h_bump(clf, 18, add18 as u32);
        h_bump(clf, 17, add17 as u32);
        h_bump(clf, 0, add0 as u32);
        h_bump(clf, 16, add16 as u32);
        h_bump(clf, v % 19, addv as u32);
        let ex = add18.wrapping_mul(7).wrapping_add(add17.wrapping_mul(3)).wrapping_add(add16.wrapping_mul(2));
        extra = extra.wrapping_add(ex as u64);
        let st = h_clamp1(run, m - i);
        i += st;
    }
    extra
}

pub fn h_dot(f: &[u32], foff: usize, l: &[u32], loff: usize, m: usize) -> u64 {
    let mut s = 0u64;
    let mut i = 0usize;
    while i < m {
        s = s.wrapping_add((h_get(f, foff.wrapping_add(i)) as u64).wrapping_mul(h_get(l, loff.wrapping_add(i)) as u64));
        i += 1;
    }
    s
}

pub fn h_fixed_dot(f: &[u32], foff: usize) -> u64 {
    let mut s = 0u64;
    let mut i = 0usize;
    while i < 288 {
        s = s.wrapping_add((h_get(f, foff.wrapping_add(i)) as u64).wrapping_mul(h_fixed_len(i) as u64));
        i += 1;
    }
    s
}

pub fn h_sum_range(f: &[u32], a: usize, b: usize) -> u64 {
    let mut s = 0u64;
    let mut i = a;
    while i < b {
        s = s.wrapping_add(h_get(f, i) as u64);
        i += 1;
    }
    s
}

pub fn h_last_nz(l: &[u32], off: usize, m: usize, lo: usize) -> usize {
    let mut k = m;
    while k > lo {
        if h_get(l, off.wrapping_add(k - 1)) != 0 {
            break;
        }
        k -= 1;
    }
    k
}

pub fn h_copy32(src: &[u32], soff: usize, dst: &mut [u32], doff: usize, m: usize) {
    let mut i = 0usize;
    while i < m {
        h_set(dst, doff.wrapping_add(i), h_get(src, soff.wrapping_add(i)));
        i += 1;
    }
}

pub fn h_hclen_of(cl: &[u32]) -> usize {
    let mut h = 19usize;
    while h > 4 {
        if h_get(cl, H_CL_ORDER[(h - 1) % 19]) != 0 {
            break;
        }
        h -= 1;
    }
    h
}

pub fn h_block_bits(fr: &mut [u32], off: usize, lens: &mut [u32]) -> u64 {
    h_bump(fr, off.wrapping_add(256), 1);
    h_pkg_merge(fr, off, 288, 15, lens, 0);
    h_pkg_merge(fr, off.wrapping_add(288), 30, 15, lens, 288);
    let ndist = h_sum_range(fr, off.wrapping_add(288), off.wrapping_add(318));
    let l288 = h_get(lens, 288);
    h_set(lens, 288, h_sel32(h_lt64(ndist, 1), 1, l288));
    let hlit = h_last_nz(lens, 0, 288, 257);
    let hdist = h_last_nz(lens, 288, 30, 1);
    let mut all = [0u32; 320];
    h_copy32(lens, 0, &mut all, 0, hlit);
    h_copy32(lens, 288, &mut all, hlit, hdist);
    let mut clf = [0u32; 19];
    let rextra = h_rle_stats(&all, hlit.wrapping_add(hdist), &mut clf);
    let mut cl = [0u32; 19];
    h_pkg_merge(&clf, 0, 19, 7, &mut cl, 0);
    let hclen = h_hclen_of(&cl);
    let ex = h_get(fr, off.wrapping_add(318)) as u64;
    let hdr = 17u64.wrapping_add(3u64.wrapping_mul(hclen as u64)).wrapping_add(h_dot(&clf, 0, &cl, 0, 19)).wrapping_add(rextra);
    let dl = h_dot(fr, off, lens, 0, 288);
    let dd = h_dot(fr, off.wrapping_add(288), lens, 288, 30);
    let dynb = hdr.wrapping_add(dl).wrapping_add(dd).wrapping_add(ex);
    let fixb = 3u64.wrapping_add(h_fixed_dot(fr, off)).wrapping_add(5u64.wrapping_mul(ndist)).wrapping_add(ex);
    h_bump(fr, off.wrapping_add(256), 0u32.wrapping_sub(1));
    let raw = h_get(fr, off.wrapping_add(319)) as u64;
    let stb = 35u64.wrapping_add(8u64.wrapping_mul(raw));
    let fx = h_lt64(dynb, fixb) ^ 1;
    let best = h_sel64(fx, fixb, dynb);
    let usest = h_lt64(ndist, 1) & h_lt64(raw, 65536) & h_lt64(stb, best);
    h_sel64(usest, stb.wrapping_mul(4).wrapping_add(2), best.wrapping_mul(4).wrapping_add(fx as u64))
}

pub const H_LOG2F: [u32; 32] = [0, 1, 1, 2, 3, 3, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13, 13, 14, 14, 15, 15, 15, 16];

pub fn h_log2x16(x: u64) -> u32 {
    if x == 0 {
        return 0;
    }
    let k = 63u32.wrapping_sub(x.leading_zeros()) % 64;
    let y = x << ((63 - k) % 64);
    let m = ((y >> 58) as usize) % 32;
    k.wrapping_mul(16).wrapping_add(H_LOG2F[m])
}

pub fn h_sym_costs(fr: &[u32], off: usize, lens: &[u32], kind: u32, sc: &mut [u32]) {
    let tl = h_sum_range(fr, off, off.wrapping_add(286)).wrapping_add(1);
    let td = h_sum_range(fr, off.wrapping_add(288), off.wrapping_add(318));
    let lt = h_log2x16(tl);
    let ld = h_log2x16(td);
    let mut s = 0usize;
    while s < 318 {
        let f = h_get(fr, off.wrapping_add(s)) as u64;
        let ls = h_get(lens, s);
        let fl = h_fixed_len(s);
        let lf = h_log2x16(f);
        let hl = if kind == 1 {
            if s >= 288 {
                5
            } else {
                fl
            }
        } else if kind == 2 && s < 256 {
            8
        } else if ls > 0 {
            ls
        } else {
            H_UNUSED
        };
        let tot = if s >= 288 { ld } else { lt };
        let e0 = if f > 0 { tot.saturating_sub(lf) } else { tot.saturating_add(H_UPEN) };
        let e = if e0 < 16 { 16 } else { e0 };
        let hc = hl.wrapping_mul(H_SC);
        let mixv = (e.wrapping_mul(H_EW).wrapping_add(hc.wrapping_mul(8 - H_EW))) / 8;
        h_set(sc, s, if kind != 0 { hc } else { mixv });
        s += 1;
    }
}

pub fn h_mode_ov(damp:u32)->u32 { if damp==2 {1} else {H_OV} }

pub fn h_blend(old: u32, new: u32, damp: u32) -> u32 {
    if damp == 0 {
        new
    } else if H_OV > 0 {
        let dlt = if new >= old { new.wrapping_sub(old) } else { old.wrapping_sub(new) };
        let adj = ((dlt as u64).wrapping_mul(h_mode_ov(damp) as u64) / 8) as u32;
        let v = if new >= old { new.saturating_add(adj) } else { new.saturating_sub(adj) };
        if v < 16 {
            16
        } else {
            v
        }
    } else {
        (((old as u64).wrapping_mul(H_DW as u64).wrapping_add((new as u64).wrapping_mul((8 - H_DW) as u64))) / 8) as u32
    }
}

pub fn h_fill_table(sc: &[u32], tbl: &mut [u32], toff: usize, damp: u32) {
    let mut c = 0usize;
    while c < 256 {
        let j = toff.wrapping_add(c);
        h_set(tbl, j, h_blend(h_get(tbl, j), h_get(sc, c), damp));
        c += 1;
    }
    let mut len = 0usize;
    while len < 259 {
        let lc = h_lcode(len);
        let v = h_get(sc, lc.wrapping_add(257)).wrapping_add(h_lextra(lc).wrapping_mul(H_SC));
        let j = toff.wrapping_add(256).wrapping_add(len);
        h_set(tbl, j, h_blend(h_get(tbl, j), v, damp));
        len += 1;
    }
    let mut s = 0usize;
    while s < 30 {
        let v = h_get(sc, s.wrapping_add(288)).wrapping_add(h_dextra(s).wrapping_mul(H_SC));
        let j = toff.wrapping_add(515).wrapping_add(s);
        h_set(tbl, j, h_blend(h_get(tbl, j), v, damp));
        s += 1;
    }
}

pub fn h_longest(mstart: &[u32], mc: &[u32], p: usize) -> usize {
    let ms = h_get(mstart, p) as usize;
    let me = h_get(mstart, p.wrapping_add(1)) as usize;
    let m = h_get(mc, me.wrapping_sub(1)) as usize;
    let l0 = m / 1048576;
    let l = h_sel(h_ge(l0, 512), l0.wrapping_sub(512), l0);
    h_sel(h_lt(ms, me), l.wrapping_mul(65536).wrapping_add(m % 32768 + 1), 1)
}

pub fn h_block_hist(input: &[u8], a: usize, b: usize, fr: &mut [u32]) {
    let mut i = a;
    while i < b {
        h_bump(fr, h_byte_at(input, i), 1);
        i += 1;
    }
}

pub fn h_add_hist(fr: &[u32], hist: &mut [u32; 256]) {
    let mut c = 0usize;
    while c < 256 {
        hist[c] = hist[c].wrapping_add(h_get(fr, c));
        c += 1;
    }
}

pub fn h_block_bits_if(fr: &mut [u32], lens: &mut [u32], f: usize) -> u64 {
    if f == 1 {
        h_block_bits(fr, 0, lens)
    } else {
        0
    }
}

pub fn h_literal_bits(input: &[u8], fr: &mut [u32], hist: &mut [u32; 256], tlit: &mut [u32], t5: &mut [u32]) -> u64 {
    let n = input.len();
    let mut lens = [0u32; 320];
    let mut sc = [0u32; 320];
    let mut total = 0u64;
    let nblk = n / H_BT + 1;
    let mut b = 0usize;
    while b < nblk {
        let p = b.wrapping_mul(H_BT);
        let e = h_sel(h_ge(p, n), p, h_sel(h_lt(H_BT, n.wrapping_sub(p)), p.wrapping_add(H_BT), n));
        h_clear(fr, 0, H_FB);
        h_block_hist(input, p, e, fr);
        h_add_hist(fr, hist);
        h_set(fr, 319, e.wrapping_sub(p) as u32);
        let r = h_block_bits_if(fr, &mut lens, h_lt(p, e));
        total = total.wrapping_add(r / 4);
        h_sym_costs(fr, 0, &lens, (r % 4) as u32, &mut sc);
        h_fill_table(&sc, tlit, b.wrapping_mul(H_TB), 0);
        h_init5_table(fr, t5, b.wrapping_mul(H_TB));
        b += 1;
    }
    total
}

pub fn h_ent5(lt: u32, f: u64) -> u32 {
    let e0 = if f > 0 { lt.saturating_sub(h_log2x16(f)) } else { lt.saturating_add(H_U5) };
    if e0 < 16 {
        16
    } else {
        e0
    }
}

pub fn h_st5len(len: usize) -> u32 {
    let lc = h_lcode(len);
    let base = if lc < 8 { 7u32 } else { 8u32 };
    (base.wrapping_add(h_lextra(lc))).wrapping_mul(16).saturating_sub(H_D5)
}

pub fn h_init5_table(fr: &[u32], tbl: &mut [u32], toff: usize) {
    let lt = h_log2x16(h_sum_range(fr, 0, 256));
    let mut c = 0usize;
    while c < 256 {
        h_set(tbl, toff.wrapping_add(c), h_ent5(lt, h_get(fr, c) as u64));
        c += 1;
    }
    let mut len = 0usize;
    while len < 259 {
        h_set(tbl, toff.wrapping_add(256).wrapping_add(len), h_st5len(len));
        len += 1;
    }
    let mut s = 0usize;
    while s < 30 {
        h_set(tbl, toff.wrapping_add(515).wrapping_add(s), (5u32.wrapping_add(h_dextra(s))).wrapping_mul(16));
        s += 1;
    }
    h_set(tbl, toff.wrapping_add(545), 0);
}

pub fn h_avg_lit16_h(hist: &[u32; 256], n: usize) -> u32 {
    let mut lens = [0u32; 320];
    h_pkg_merge(hist, 0, 256, 15, &mut lens, 0);
    let tot = h_dot(hist, 0, &lens, 0, 256);
    let q = (tot.wrapping_mul(16) / h_nz64(n as u64)) as u32;
    if n > 0 {
        q
    } else {
        128
    }
}

pub fn h_est_match16(l: usize, d: usize) -> u32 {
    let lc = h_lcode(l);
    let s = h_dslot(d);
    (12u32.wrapping_add(h_lextra(lc)).wrapping_add(h_dextra(s))).wrapping_mul(16).wrapping_add(H_MBIAS)
}

pub fn h_est_if(f: usize, l: usize, d: usize) -> u32 {
    if f == 1 {
        h_est_match16(l, d)
    } else {
        0
    }
}

pub fn h_next_longest(mstart: &[u32], mc: &[u32], pos: usize, st: usize, b: usize) -> usize {
    if st == 1 {
        b
    } else {
        h_longest(mstart, mc, pos.wrapping_add(st))
    }
}

pub fn h_lazy_cost_init(input: &[u8], mstart: &[u32], mc: &[u32], h16: u32, choice: &mut [u32]) {
    let n = input.len();
    let mut pos = 0usize;
    let mut nxt = h_longest(mstart, mc, 0);
    let mut ec = 0u32;
    let mut hv = 0usize;
    while pos < n {
        let a = nxt;
        let b = h_longest(mstart, mc, pos.wrapping_add(1));
        let al = a / 65536;
        let ad = a % 65536;
        let bl = b / 65536;
        let bd = b % 65536;
        let room = n - pos;
        let ea = h_sel32(hv, ec, h_est_if(h_ge(al, 3) & (hv ^ 1), al, ad));
        let eb = h_est_if(h_lt(al, bl), bl, bd);
        let oka = h_ge(al, 3) & h_ge(room, al) & h_lt32(ea, (al as u32).wrapping_mul(h16));
        let okb = h_lt(al, bl) & h_lt32(eb, (bl as u32).wrapping_mul(h16));
        let tl = h_sel(oka & (okb ^ 1), al, 0);
        h_set(choice, pos, h_sel32(h_ge(tl, 3), (tl as u32).wrapping_mul(65536).wrapping_add(ad as u32), 0));
        let st = h_clamp_step(tl, room);
        nxt = h_next_longest(mstart, mc, pos, st, b);
        // the next position's match is b when st == 1: reuse its estimate when it was computed.
        hv = h_eq(st, 1) & h_lt(al, bl);
        ec = eb;
        pos += st;
    }
}

pub fn h_forbid_block(tbl: &mut [u32], toff: usize) {
    let mut len = 0usize;
    while len < 259 {
        h_set(tbl, toff.wrapping_add(256).wrapping_add(len), H_BIG);
        len += 1;
    }
}

pub fn h_forbid_if(tbl: &mut [u32], toff: usize, f: usize) {
    if f == 1 {
        h_forbid_block(tbl, toff);
    }
}

pub fn h_eval_blocks(fr: &mut [u32], tbl: &mut [u32], nb2: usize, nbmax: usize, damp: u32) -> u64 {
    let mut lens = [0u32; 320];
    let mut sc = [0u32; 320];
    let mut total = 0u64;
    let lim = h_umin(nb2, nbmax);
    let mut b = 0usize;
    while b < lim {
        let r = h_block_bits(fr, b.wrapping_mul(H_FB), &mut lens);
        total = total.wrapping_add(r / 4);
        h_sym_costs(fr, b.wrapping_mul(H_FB), &lens, (r % 4) as u32, &mut sc);
        h_fill_table(&sc, tbl, b.wrapping_mul(H_TB), damp);
        let raw = h_get(fr, b.wrapping_mul(H_FB).wrapping_add(319)) as u64;
        let fb = h_eq(H_STM, 1) & h_lt64(raw.wrapping_mul(8).wrapping_add(35).wrapping_add(H_STMARG), r / 4);
        let fl = ((h_get(tbl, b.wrapping_mul(H_TB).wrapping_add(545)) as usize) | fb) & 1;
        h_set(tbl, b.wrapping_mul(H_TB).wrapping_add(545), fl as u32);
        h_forbid_if(tbl, b.wrapping_mul(H_TB), fl);
        b += 1;
    }
    total
}

pub fn h_dp_pass(
    input: &[u8],
    mstart: &[u32],
    mc: &[u32],
    tbl: &[u32],
    bend: &[u32; 512],
    bpos: &[u32],
    nb: usize,
    choice: &mut [u32],
    chw: usize,
    keep: usize,
    items: &mut Vec<u32>,
    istart: &mut Vec<u32>,
    pr: usize,
    msub: u32,
    co: usize,
    lam: u32,
) {
    if pr == 0 {
        h_pass_prune(input, mstart, mc, tbl, bend, bpos, nb, choice, chw, msub, keep, items, istart, co, lam);
    } else {
        h_pass_items(input, tbl, bpos, nb, choice, items, istart, h_ge(chw, 15), co, lam);
    }
}

pub fn h_stop_rule(prev: u64, r: u64, n: usize, it1: usize, gk: u64, minp: usize) -> usize {
    let gain = if prev > r { prev.wrapping_sub(r) } else { 0 };
    let f1 = h_sel64(h_eq(it1, 1), H_F1, 1);
    let n1 = h_nz64(n as u64);
    let nn = n1.wrapping_mul(n1);
    let t2 = (gain.wrapping_mul(r) / n1).wrapping_mul(r) / n1;
    let small2 = h_lt64(t2.wrapping_mul(1280), n1.wrapping_mul(gk).wrapping_mul(f1));
    let smallg = h_lt64(gain.wrapping_mul(r).wrapping_mul(1024), nn.wrapping_mul(H_GAINK).wrapping_mul(f1));
    let smalle = h_lt64(r.wrapping_add(r >> H_ESH), prev) ^ 1;
    let small = if H_RALPHA == 2 { small2 } else if H_GAINK > 0 { smallg } else { smalle };
    h_ge(it1, minp) & small
}

pub fn h_one_pass(prev: u64, n: usize, gk: u64) -> usize {
    let n1 = h_nz64(n as u64);
    let q = (h_umin64(prev, 1099511627776).wrapping_mul(256).wrapping_add(n1.wrapping_sub(1))) / n1;
    let lhs = q.wrapping_mul(q).wrapping_mul(q).wrapping_mul(5120);
    let rhs = gk.wrapping_mul(H_F1).wrapping_mul(27).wrapping_mul(16777216);
    (h_eq(H_RALPHA as usize, 2) & h_ge(1, H_MINIT) & h_lt64(q, 4096) & h_lt64(lhs, rhs)) | h_lt64(q, H_OPQ)
}

pub fn h_iterate(mode: usize, 
    input: &[u8],
    mstart: &[u32],
    mc: &[u32],
    tbl: &mut [u32],
    fr: &mut [u32],
    bpos: &mut [u32],
    bend: &[u32; 512],
    choice: &mut [u32],
    plan: &mut [u32],
    nbmax: usize,
    nb0: usize,
    best0: u64,
    prev0: u64,
    gk: u64,
    lamh: u32,
    minp: usize,
    ew:u32,
) {
    let n = input.len();
    let mut nb = nb0;
    let mut best = best0;
    let mut prev = prev0;
    let mut stop = 0usize;
    let mut it = 0usize;
    let mut items: Vec<u32> = Vec::with_capacity(n.wrapping_mul(2).wrapping_add(64));
    let mut istart: Vec<u32> = Vec::with_capacity(n.wrapping_add(1));
    let kp0 = (h_one_pass(prev0, n, gk) ^ 1) | h_lt(1, minp);
    let mut pr = 0usize;
    // double-buffered choice: pass results alternate between halves; bh = half holding the best plan (2: `plan`).
    let mut wh = 0usize;
    let mut bh = 2usize;
    let chw = h_sel(h_ge(n, H_CHN), H_CHW, H_CHWS);
    while it < H_ITERS && stop == 0 {
        let it1 = it + 1;
        let kp = kp0 | h_ge(it, 1);
        if mode == 4 && it == 2 && gk < 16 { h_cx_jitter(tbl, nb, 1, 32); }
        // @DP_BEGIN
        let co = wh.wrapping_mul(n.wrapping_add(1));
        h_dp_pass(input, mstart, mc, tbl, bend, bpos, nb, choice, chw, kp, &mut items, &mut istart, pr, h_sel32(h_eq(it, 0), H_MDEL, H_MDEL2), co, lamh);
        // @DP_END
        pr = pr | kp;
        // @P6_BEGIN
        let nb2 = h_walk(input, mstart, mc, choice, co, fr, bpos);
        let r = h_eval_mode(mode, fr, tbl, nb2, nbmax, h_ge(it1, H_DSTART) as u32,ew);
        // @P6_END
        nb = nb2;
        let imp = h_lt64(r, best);
        bh = h_sel(imp, wh, bh);
        wh = h_sel(imp, wh ^ 1, wh);
        best = h_sel64(imp, r, best);
        stop = h_stop_rule(prev, r, n, it1, gk, minp);
        if mode == 4 { stop = stop & ((h_lt(it,5) & h_lt64(gk,16)) ^ 1); }
        prev = r;
        it = it1;
    }
    h_copy32(choice, bh.wrapping_mul(n.wrapping_add(1)), plan, 0, h_sel(h_lt(bh, 2), n, 0));
    if mode == 2 || mode == 3 || mode == 5 || mode == 6 {
        let restarts = if mode == 3 { 2 } else if (mode == 5 || mode == 6) && prev <= best { 0 } else { 1 };
        h_cx_restarts(input, mstart, mc, tbl, fr, bpos, bend, choice, plan,
                    nbmax, lamh, &mut items, &mut istart, pr, chw, restarts);
    }
}

pub fn h_lit_bpos(bpos: &mut [u32], m: usize) {
    let mut b = 0usize;
    while b < m {
        h_set(bpos, b, (b.wrapping_mul(H_BT)) as u32);
        b += 1;
    }
}

pub fn h_optimize(mode: usize, 
    input: &[u8],
    mstart: &[u32],
    mc: &[u32],
    tbl: &mut [u32],
    fr: &mut [u32],
    bpos: &mut [u32],
    bend: &[u32; 512],
    choice: &mut [u32],
    plan: &mut [u32],
    nbmax: usize,
    gk: u64,
    i5: usize,
) {
    let n = input.len();
    h_find_spare(input, h_lt(n, 4));
    // @P5_BEGIN
    let mut hist = [0u32; 256];
    let mut tlit = h_filled(nbmax.wrapping_mul(H_TB), 0);
    let mut t5 = h_filled(nbmax.wrapping_mul(H_TB), 0);
    let rl = h_literal_bits(input, fr, &mut hist, &mut tlit, &mut t5);
    let h16 = h_avg_lit16_h(&hist, n);
    let ew=if mode == 0 { h_sel32(h_lt(h_entropy256(&hist),H_HGEN),1,h_sel32(h_eq64(gk,H_GKMC),0,h_sel32(h_eq64(gk,H_GKLOW),2,3))) } else { 0 };
    h_lazy_cost_init(input, mstart, mc, h16, choice);
    let nb0 = h_walk(input, mstart, mc, choice, 0, fr, bpos);
    let r0 = h_eval_mode(mode, fr, tbl, nb0, nbmax, 0,ew);
    let lz = h_lt64(r0, rl);
    h_copy32(choice, 0, plan, 0, h_sel(lz, n, 0));
    let best0 = h_sel64(lz, r0, rl);
    // H_STARTBEST: start from the all-literal path's tables (computed by literal_bits) when it is better.
    // high-entropy inputs (best start above H_HBPB/8 bits per byte): init5 tables, per-token reward H_LAMH.
    let hi = h_lt64((n as u64).wrapping_mul(H_HBPB) / 8, best0) & i5;
    let sb = (h_eq(H_STARTBEST, 1) & h_lt64(rl, r0)) | hi;
    h_copy32(&tlit, 0, tbl, 0, h_sel(sb, nbmax.wrapping_mul(H_TB), 0));
    h_copy32(&t5, 0, tbl, 0, h_sel(hi, nbmax.wrapping_mul(H_TB), 0));
    let nbl = h_sel(h_lt(0, n), n.wrapping_add(H_BT - 1) / H_BT, 1);
    h_lit_bpos(bpos, h_sel(sb, nbl, 0));
    let nbst = h_sel(sb, nbl, nb0);
    let prev0 = h_sel64(sb, rl, r0);
    // @P5_END
    h_iterate(mode, input, mstart, mc, tbl, fr, bpos, bend, choice, plan, nbmax, nbst, best0, prev0, gk, h_sel32(hi, H_LAMH, 0), h_sel(hi, H_MINH, H_MINIT),ew);
}

pub fn h_champ(mode: usize, input: &[u8], plan: &mut [u32], gk: u64, i5: usize) {
    let n = input.len();
    let mut mstart: Vec<u32> = Vec::with_capacity(n.wrapping_add(1));
    let mut mc: Vec<u32> = Vec::with_capacity(n.wrapping_mul(3).wrapping_add(64));
    // @FIND_BEGIN
    h_find_all(input, &mut mstart, &mut mc, h_sel(h_lt(n, H_SMALLN), H_BTDS, h_sel(h_eq64(gk, h_mode_gk(mode, H_GKMC)), H_BTDMC, h_sel(h_eq64(gk, h_mode_gk(mode, H_GKX)), h_sel(h_eq(mode,6),24,H_BTDX), H_BTD))));
    // @FIND_END
    let nbmax = n / H_BT + 2;
    let mut tbl = h_filled(nbmax.wrapping_mul(H_TB), 0);
    let mut fr = h_filled(nbmax.wrapping_mul(H_FB), 0);
    let mut bpos = h_filled(nbmax, 0);
    let mut bend = [0u32; 512];
    h_build_bend(&mut bend);
    let mut choice = h_filled(n.wrapping_add(1).wrapping_mul(2), 0);
    h_optimize(mode, input, &mstart, &mc, &mut tbl, &mut fr, &mut bpos, &bend, &mut choice, plan, nbmax, gk, i5);
}

pub fn h_champ_if(mode: usize, input: &[u8], plan: &mut [u32], on: usize, gk: u64, i5: usize) {
    if on == 1 {
        h_champ(mode, input, plan, gk, i5);
    }
}

pub const H_D_SMALL: usize = 65536;

pub const H_PR_W: usize = 8192;

pub const H_PR_N: usize = 8;

pub const H_LITCOV: u64 = 8;

pub const H_HLIT: usize = 1984;

pub const H_LONGL: usize = 32;

pub const H_LONGK: u64 = 340;

pub const H_COVF: u64 = 150;

pub const H_GKLOW: u64 = 32;

pub const H_HGEN: usize = 896;

pub const H_HGENLO: usize = 448;

pub const H_DEFM: usize = 0;

pub const H_COVT: u64 = 655;

pub const H_LONGT: u64 = 100;

pub const H_H_KENDS: [usize; 4] = [20, 20, 20, 20];

pub const H_DIGR: u64 = 150;

pub const H_Z0IM: u64 = 8;

pub const H_HSP: usize = 0;

pub const H_NZR: u64 = 81;

pub const H_CTLMC: u64 = 120;

pub const H_HIMC: u64 = 400;

pub const H_NMMC: u64 = 440;

pub const H_HITC: u64 = 160;

pub const H_CTLMB: u64 = 20;

pub const H_GKMC: u64 = 4;

pub const H_BTDMC: usize = 32;

pub const H_GKT: u64 = 8;

pub const H_GKX: u64 = 2;

pub const H_HBF: usize = 1650;

pub const H_BTDX: usize = 32;

pub fn h_hash12(input: &[u8], p: usize) -> usize {
    let n = input.len();
    if n >= 4 && p <= n - 4 {
        let x = (input[p] as u32) | ((input[p + 1] as u32) << 8) | ((input[p + 2] as u32) << 16) | ((input[p + 3] as u32) << 24);
        ((x.wrapping_mul(2654435761) >> 20) as usize) % 4096
    } else {
        0
    }
}

pub fn h_probe_win(input: &[u8], ht: &mut [u32; 4096], s: usize, e: usize) -> u64 {
    let n = input.len();
    let mut i = s;
    let mut cov = 0u64;
    let mut nm = 0u64;
    let mut it = 0usize;
    while it < H_PR_W && i < e {
        let h = h_hash12(input, i);
        let c = ht[h % 4096] as usize;
        ht[h % 4096] = (i as u32).wrapping_add(1);
        let cm = c.wrapping_sub(1);
        let ok = h_lt(s, c) & h_lt(cm, i) & h_lt(i.wrapping_add(8), n);
        let cap = h_umin(e.wrapping_sub(i), 258);
        let l = h_ext_if(input, ok, cm, i, 0, cap, 0);
        let hit = h_ge(l, 4);
        cov = cov.wrapping_add(h_sel(hit, l, 0) as u64);
        nm = nm.wrapping_add(h_sel(h_ge(l, H_LONGL), l, 0) as u64);
        i = i.wrapping_add(h_sel(hit, l, 1));
        it += 1;
    }
    cov.wrapping_mul(4294967296).wrapping_add(nm)
}

pub fn h_probe_all(input: &[u8]) -> u64 {
    let n = input.len();
    let mut ht = [0u32; 4096];
    let span = n.wrapping_sub(H_PR_W) / (H_PR_N - 1);
    let mut acc = 0u64;
    let mut k = 0usize;
    while k < H_PR_N {
        let s = span.wrapping_mul(k);
        acc = acc.wrapping_add(h_probe_win(input, &mut ht, s, s.wrapping_add(H_PR_W)));
        k += 1;
    }
    acc
}

pub fn h_probe_if(input: &[u8], f: usize) -> u64 {
    if f == 1 {
        h_probe_all(input)
    } else {
        0
    }
}

pub fn h_odd_sample(input: &[u8], h: &mut [u32; 256]) {
    let n = input.len();
    let st = (n / 4096 + 1) | 1;
    let mut k = 0usize;
    let mut c = 0usize;
    while c < 8192 && k < n {
        let b = h_byte_at(input, k) % 256;
        h[b] = h[b].wrapping_add(1);
        k = k.wrapping_add(st);
        c += 1;
    }
}

pub fn h_lg8(x: u32) -> u64 {
    let y = x | 1;
    let e = 31u32.wrapping_sub(y.leading_zeros()) % 32;
    let m = if e >= 8 { y.wrapping_shr(e.wrapping_sub(8)) & 255 } else { y.wrapping_shl(8u32.wrapping_sub(e)) & 255 };
    (e as u64).wrapping_mul(256).wrapping_add(m as u64)
}

pub fn h_entropy256(h: &[u32; 256]) -> usize {
    let mut tot = 0u64;
    let mut acc = 0u64;
    let mut i = 0usize;
    while i < 256 {
        let c = h[i];
        tot = tot.wrapping_add(c as u64);
        acc = if c > 0 { acc.wrapping_add((c as u64).wrapping_mul(h_lg8(c))) } else { acc };
        i += 1;
    }
    let t32 = if tot > 4000000000 { 4000000000u32 } else { tot as u32 };
    let a = h_lg8(t32);
    let b = if tot == 0 { 0 } else { acc / tot };
    if tot == 0 {
        2048
    } else if a > b {
        (a - b) as usize
    } else {
        0
    }
}

pub fn h_ge64(a: u64, b: u64) -> usize {
    if a >= b {
        1
    } else {
        0
    }
}

pub fn h_classify(input: &[u8]) -> usize {
    let n = input.len();
    let small = h_lt(n, H_D_SMALL);
    let r = h_probe_if(input, small ^ 1);
    let cov = r / 4294967296;
    let nm = r % 4294967296;
    let mut lh = [0u32; 256];
    h_odd_sample(input, &mut lh);
    let h0 = h_entropy256(&lh);
    let bc = h_byte_classes(&lh);
    let b2 = h_byte_classes2(&lh);
    let tot = bc % 1048576;
    let ctl = (bc / 1048576) % 1048576;
    let hib = (bc / 1099511627776) % 1048576;
    let pw = (H_PR_W * H_PR_N) as u64;
    let low = h_lt64(cov.wrapping_mul(1000), H_LITCOV.wrapping_mul(pw));
    let hl = h_ge64(nm.wrapping_mul(1000), H_LONGK.wrapping_mul(pw));
    let lc = h_lt64(cov.wrapping_mul(1000), H_COVF.wrapping_mul(pw));
    let hi = h_ge(h0, H_HLIT);
    let gen = h_lt(h0, H_HGEN) & h_ge(h0, H_HGENLO);
    let tc0 = h_lt64(cov.wrapping_mul(1000), H_COVT.wrapping_mul(pw)) & h_lt64(nm.wrapping_mul(1000), H_LONGT.wrapping_mul(pw));
    let mb = h_ge64(hib.wrapping_mul(1000), H_HITC.wrapping_mul(tot)) & h_lt64(ctl.wrapping_mul(1000), H_CTLMB.wrapping_mul(tot));
    let tc = tc0 & (mb ^ 1);
    let mc = (small ^ 1) & h_ge64(ctl.wrapping_mul(1000), H_CTLMC.wrapping_mul(tot)) & h_lt64(hib.wrapping_mul(1000), H_HIMC.wrapping_mul(tot)) & h_lt64(nm.wrapping_mul(1000), H_NMMC.wrapping_mul(pw));
    let ch = (lc & (hi ^ 1)) | gen | tc | mc;
    let m0 = h_sel(hl | lc, 1, H_DEFM);
    let m1 = h_sel(ch, 0, m0);
    let z0 = b2 % 65536;
    let im = h_ge64(z0.wrapping_mul(1000), H_Z0IM.wrapping_mul(tot));
    let bf = h_lt(h0, H_HBF);
    let m2 = h_sel(low, h_sel(hi, h_sel(im, 0, 1), h_sel(bf, 0, 2)), m1);
    let gkc = h_sel(lc, h_sel(hi, 4, 1), h_sel(mc, 2, h_sel(tc, 3, h_sel(gen, 0, 5))));
    let dig = (b2 / 65536) % 65536;
    let nz = (b2 / 4294967296) % 65536;
    let dh = (hl | small) & h_eq64(z0, 0) & h_ge64(dig.wrapping_mul(1000), H_DIGR.wrapping_mul(tot)) & h_ge64(H_NZR, nz);
    let sp = small & h_lt(h0, H_HSP);
    let fc = h_sel(dh | sp, 2, h_sel(hl | small, 1, 0));
    h_sel(small, 1, m2).wrapping_add(gkc.wrapping_mul(4)).wrapping_add(fc.wrapping_mul(32))
}

pub fn h_byte_classes2(h: &[u32; 256]) -> u64 {
    let mut z0 = 0u64;
    let mut dig = 0u64;
    let mut nz = 0u64;
    let mut i = 0usize;
    while i < 256 {
        let c = h[i] as u64;
        z0 = z0.wrapping_add(h_sel64(h_eq(i, 0), c, 0));
        dig = dig.wrapping_add(h_sel64(h_ge(i, 48) & h_lt(i, 58), c, 0));
        nz = nz.wrapping_add(h_sel64(h_lt64(0, c), 1, 0));
        i += 1;
    }
    (z0 % 65536).wrapping_add((dig % 65536).wrapping_mul(65536)).wrapping_add((nz % 65536).wrapping_mul(4294967296))
}

pub fn h_byte_classes(h: &[u32; 256]) -> u64 {
    let mut tot = 0u64;
    let mut ctl = 0u64;
    let mut hib = 0u64;
    let mut i = 0usize;
    while i < 256 {
        let c = h[i] as u64;
        tot = tot.wrapping_add(c);
        let isc = (h_lt(i, 32) & h_ge(i, 1)) & ((h_eq(i, 9) | h_eq(i, 10) | h_eq(i, 13)) ^ 1);
        ctl = ctl.wrapping_add(h_sel64(isc, c, 0));
        hib = hib.wrapping_add(h_sel64(h_ge(i, 128), c, 0));
        i += 1;
    }
    (tot % 1048576).wrapping_add((ctl % 1048576).wrapping_mul(1048576)).wrapping_add((hib % 1048576).wrapping_mul(1099511627776))
}

pub fn h_parse_mode(input: &[u8], out: &mut [u32], mode: usize) -> usize {
    let cmode = mode;
    let mode = mode % 8;
    let n = input.len();
    let c = h_classify(input);
    let route = 0usize;
    let gkc = (c / 4) % 8;
    let gk = h_sel64(h_eq(gkc, 1) | h_eq(gkc, 4), h_mode_gk(mode, H_GKLOW), h_sel64(h_eq(gkc, 2), h_mode_gk(mode, H_GKMC), h_sel64(h_eq(gkc, 3), h_mode_gk(mode, H_GKT), h_sel64(h_eq(gkc, 5), h_mode_gk(mode, H_GKX), h_mode_gk(mode, H_GK2)))));
    let fc = (c / 32) % 4;
    let kend = H_H_KENDS[fc % 4].wrapping_add(fc.wrapping_mul(32));
    let mut plan = h_filled(n.wrapping_add(1), 0);
    h_champ_if(mode, input, &mut plan, h_eq(route, 0), gk, h_eq(gkc, 1));
    let high = h_eq(mode, 2) | h_eq(mode, 3) | (h_eq(mode, 5) | h_eq(mode, 6));
    let force = high & h_eq(route, 1) & h_ge(n, H_D_SMALL);
    // @P7_BEGIN
    let nt = h_emit_all(input, out, &plan);
    // @P7_END
    nt
}

pub fn h_pkg_merge(freq:&[u32],off:usize,nsym:usize,maxbits:usize,lens:&mut [u32],loff:usize) {
    let mut order=[0u32;288];
    let k=h_sort_live(freq,off,nsym,&mut order);
    let mut weights=[0u64;576];
    let mut parent=[0u32;576];
    let mut depth=[0u32;576];
    let mut i=0usize;
    while i<k && i<288 {weights[i]=h_get(freq,off.wrapping_add(order[i] as usize)) as u64;i+=1;}
    let mut leaf=0usize;
    let mut pair=k;
    let mut next=k;
    while next.wrapping_add(1)<k.wrapping_mul(2) && next<575 {
        let mut sum=0u64;
        let mut j=0usize;
        while j<2 {
            let lw=if leaf<k {weights[leaf%576]} else {18446744073709551615u64};
            let pw=if pair<next {weights[pair%576]} else {18446744073709551615u64};
            let take=h_lt64(pw,lw)^1;
            let idx=h_sel(take,leaf,pair);
            sum=sum.wrapping_add(weights[idx%576]);
            parent[idx%576]=next as u32;
            leaf=leaf.wrapping_add(take);
            pair=pair.wrapping_add(take^1);
            j+=1;
        }
        weights[next%576]=sum;
        next+=1;
    }
    let mut mx=0usize;
    let mut node=next.saturating_sub(1);
    while node>0 {
        node-=1;
        let d=depth[(parent[node%576] as usize)%576].wrapping_add(1);
        depth[node%576]=d;
        mx=h_umax(mx,d as usize);
    }
    if mx<=maxbits {
        h_clear(lens,loff,loff.wrapping_add(nsym));
        let mut r=0usize;
        while r<k && r<288 {
            h_set(lens,loff.wrapping_add(order[r] as usize),h_sel32(h_eq(k,1),1,depth[r]));r+=1;
        }
    } else {
        h_pkg_merge_pm(freq,off,nsym,maxbits,lens,loff);
    }
}

pub fn h_mode_gk(mode: usize, base: u64) -> u64 {
    if (mode >= 1 && mode <= 3) || mode == 5 || mode == 6 { base / 2 } else { base }
}

pub fn h_mode_damp(mode:usize,damp:u32)->u32 { if mode==6 && damp>0 {2} else {damp} }

pub fn h_eval_mode(mode: usize, fr: &mut [u32], tbl: &mut [u32], nb: usize, nbmax: usize, damp: u32, ew: u32) -> u64 {
    let damp = h_mode_damp(mode,damp);
    h_eval_blocks(fr,tbl,nb,nbmax,damp)
}

pub fn h_cx_jitter(tbl:&mut [u32],nb:usize,seed:u32, amplitude:u32) {
    let amp = amplitude % 33;
    let mut b=0usize;
    while b<nb {
        let off=b.wrapping_mul(H_TB);
        let mut s=0usize;
        while s<545 {
            let sym=if s>=256 && s<515 {257+h_lcode(s-256)} else if s>=515 {288+s-515} else {s};
            let x=(sym as u32).wrapping_mul(2654435761).wrapping_add(seed.wrapping_mul(2246822519));
            let x=(x^(x>>16)).wrapping_mul(3266489917);
            let d=(x>>24)%(2*amp+1);
            let c=h_get(tbl,off.wrapping_add(s));
            let v=c.saturating_add(d).saturating_sub(amp);
            h_set(tbl,off.wrapping_add(s),v);
            s+=1;
        }
        b+=1;
    }
}

pub fn h_cx_restarts(
    input: &[u8], mstart: &[u32], mc: &[u32], tbl: &mut [u32],
    fr: &mut [u32], bpos: &mut [u32], bend: &[u32; 512],
    choice: &mut [u32], plan: &mut [u32], nbmax: usize, lamh: u32,
    items: &mut Vec<u32>, istart: &mut Vec<u32>, pr: usize, chw: usize,
    restarts: usize,
) {
    let n = input.len();
    let jitteron = h_eq(h_classify(input) % 4, 0);
    let mut restart = 0usize;
    while restart < restarts && jitteron == 1 {
        let mut nbc = h_walk(input, mstart, mc, plan, 0, fr, bpos);
        let mut bestp = h_eval_blocks(fr, tbl, nbc, nbmax, 0);
        h_cx_jitter(tbl, nbc, (restart as u32).wrapping_add(1), 16);
        let mut step = 0usize;
        while step < 3 {
            h_dp_pass(input, mstart, mc, tbl, bend, bpos, nbc, choice, chw,
                    0, items, istart, pr, 0, 0, lamh);
            nbc = h_walk(input, mstart, mc, choice, 0, fr, bpos);
            let rp = h_eval_blocks(fr, tbl, nbc, nbmax, 0);
            let improve = h_lt64(rp, bestp);
            h_copy32(choice, 0, plan, 0, h_sel(improve, n, 0));
            bestp = h_sel64(improve, rp, bestp);
            step += 1;
        }
        restart += 1;
    }
}
