-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [slot]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace slot

/-- [slot::Y_B_Params]
    Source: '/home/runner/work/_temp/deflate-upstream/data/verification-workspace/verify-bgrvd6e4/slot/generated/parse.rs', lines 1937:0-2000:1
    Visibility: public -/
structure Y_B_Params where
  depth : Std.Usize
  depth2 : Std.Usize
  lazy : Std.Usize
  acc : Std.U64
  stepmax : Std.Usize
  h3hi : Std.Usize
  c0q : Std.Usize
  dn : Std.Usize
  p2n : Std.Usize
  fl_pnc : Std.Usize
  ft_ih : Std.Usize
  ft_it : Std.Usize
  ft_depth : Std.Usize
  ft_depth2 : Std.Usize
  ft_lazy : Std.Usize
  ft_nice : Std.Usize
  ft_acc : Std.Usize
  fd_depth : Std.Usize
  fd_depth2 : Std.Usize
  fd_lazy : Std.Usize
  fd_nice : Std.Usize
  fd_ih : Std.Usize
  fd_it : Std.Usize
  fd_acc : Std.Usize
  fh_depth : Std.Usize
  fh_depth2 : Std.Usize
  fh_lazy : Std.Usize
  fh_nice : Std.Usize
  fh_ih : Std.Usize
  fh_it : Std.Usize
  fh_acc : Std.Usize
  fl_pmin : Std.Usize
  fl_rle_top : Std.Usize
  fl_high : Std.Usize
  fl_dbz : Std.Usize
  fl_dbnp : Std.Usize
  fl_use_t : Std.Usize
  fl_use_d : Std.Usize
  fl_use_h : Std.Usize
  fl_use_lit : Std.Usize
  lqn : Std.Usize
  c0l : Std.Usize
  hsl : Std.U32
  accl : Std.U64
  nsmall : Std.Usize
  depthl : Std.Usize
  depth3m : Std.Usize
  elo : Std.Usize
  hlow : Std.Usize
  litq : Std.Usize
  ladj : Std.Usize
  m3 : Std.Usize
  m3e : Std.Usize
  m3z : Std.Usize
  h3 : Std.Usize
  h3ctl : Std.Usize
  h3e : Std.Usize
  nbig : Std.Usize
  dign : Std.Usize
  fl_litq : Std.Usize
  fl_ladj : Std.Usize
  fl_hlow : Std.Usize

/-- [slot::U118_Y_B_Params]
    Source: '/home/runner/work/_temp/deflate-upstream/data/verification-workspace/verify-bgrvd6e4/slot/generated/parse.rs', lines 4998:0-5061:1
    Visibility: public -/
structure U118_Y_B_Params where
  depth : Std.Usize
  depth2 : Std.Usize
  lazy : Std.Usize
  acc : Std.U64
  stepmax : Std.Usize
  h3hi : Std.Usize
  c0q : Std.Usize
  dn : Std.Usize
  p2n : Std.Usize
  fl_pnc : Std.Usize
  ft_ih : Std.Usize
  ft_it : Std.Usize
  ft_depth : Std.Usize
  ft_depth2 : Std.Usize
  ft_lazy : Std.Usize
  ft_nice : Std.Usize
  ft_acc : Std.Usize
  fd_depth : Std.Usize
  fd_depth2 : Std.Usize
  fd_lazy : Std.Usize
  fd_nice : Std.Usize
  fd_ih : Std.Usize
  fd_it : Std.Usize
  fd_acc : Std.Usize
  fh_depth : Std.Usize
  fh_depth2 : Std.Usize
  fh_lazy : Std.Usize
  fh_nice : Std.Usize
  fh_ih : Std.Usize
  fh_it : Std.Usize
  fh_acc : Std.Usize
  fl_pmin : Std.Usize
  fl_rle_top : Std.Usize
  fl_high : Std.Usize
  fl_dbz : Std.Usize
  fl_dbnp : Std.Usize
  fl_use_t : Std.Usize
  fl_use_d : Std.Usize
  fl_use_h : Std.Usize
  fl_use_lit : Std.Usize
  lqn : Std.Usize
  c0l : Std.Usize
  hsl : Std.U32
  accl : Std.U64
  nsmall : Std.Usize
  depthl : Std.Usize
  depth3m : Std.Usize
  elo : Std.Usize
  hlow : Std.Usize
  litq : Std.Usize
  ladj : Std.Usize
  m3 : Std.Usize
  m3e : Std.Usize
  m3z : Std.Usize
  h3 : Std.Usize
  h3ctl : Std.Usize
  h3e : Std.Usize
  nbig : Std.Usize
  dign : Std.Usize
  fl_litq : Std.Usize
  fl_ladj : Std.Usize
  fl_hlow : Std.Usize

end slot
