-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [slot]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace slot

/-- [slot::Z8]
    Source: '/home/runner/work/_temp/deflate-upstream/data/verification-workspace/verify-u073vkli/slot/generated/parse.rs', lines 1431:0-1441:1
    Visibility: public -/
structure Z8 where
  head : Array Std.U32 65536#usize
  head3 : Array Std.U32 16384#usize
  tree : Array Std.U32 65536#usize
  w : Array Std.U64 32768#usize
  pn : Array Std.U32 32#usize
  pf : Array Std.U32 32#usize
  plen : Std.Usize
  hn : Std.Usize
  hl : Std.Usize

/-- [slot::Z132]
    Source: '/home/runner/work/_temp/deflate-upstream/data/verification-workspace/verify-u073vkli/slot/generated/parse.rs', lines 7293:0-7303:1
    Visibility: public -/
structure Z132 where
  head : Array Std.U32 65536#usize
  head3 : Array Std.U32 16384#usize
  tree : Array Std.U32 65536#usize
  w : Array Std.U64 32768#usize
  pn : Array Std.U32 32#usize
  pf : Array Std.U32 32#usize
  plen : Std.Usize
  hn : Std.Usize
  hl : Std.Usize

/-- [slot::Z135]
    Source: '/home/runner/work/_temp/deflate-upstream/data/verification-workspace/verify-u073vkli/slot/generated/parse.rs', lines 7901:0-7911:1
    Visibility: public -/
structure Z135 where
  head : Array Std.U32 65536#usize
  head3 : Array Std.U32 16384#usize
  tree : Array Std.U32 65536#usize
  w : Array Std.U64 32768#usize
  pn : Array Std.U32 32#usize
  pf : Array Std.U32 32#usize
  plen : Std.Usize
  hn : Std.Usize
  hl : Std.Usize

/-- [slot::Z137]
    Source: '/home/runner/work/_temp/deflate-upstream/data/verification-workspace/verify-u073vkli/slot/generated/parse.rs', lines 9522:0-9532:1
    Visibility: public -/
structure Z137 where
  head : Array Std.U32 65536#usize
  head3 : Array Std.U32 16384#usize
  tree : Array Std.U32 65536#usize
  w : Array Std.U64 32768#usize
  pn : Array Std.U32 32#usize
  pf : Array Std.U32 32#usize
  plen : Std.Usize
  hn : Std.Usize
  hl : Std.Usize

end slot
