"""Deliver collected R22 evidence, separate confirmations, gates and forecasts."""
from pathlib import Path
from datetime import datetime,timezone
import argparse,collections,hashlib,json,statistics as st
ROOT=Path(__file__).resolve().parents[1];E=ROOT/'evidence/round22'

def read(p):return json.loads(p.read_bytes())
def write(p,v):p.write_bytes((json.dumps(v,indent=2,ensure_ascii=False)+'\n').encode())
def dist(s):return f"{s['median_pct']:.6f}%／{s['range_pct'][0]:.6f}–{s['range_pct'][1]:.6f}%"

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--analysis',type=Path,required=True);ap.add_argument('--audit',type=Path,required=True);ap.add_argument('--capture',type=Path,required=True);a=ap.parse_args()
    d,audit,budget=read(a.analysis),read(a.audit),read(E/'budget.json');assert not audit['uncollected_run_ids']
    diagnostic=read(E/'diagnostic-analysis.json');comp=read(a.capture/'competition.json');assert str(comp['current_snapshot_id'])==d['snapshot']['snapshot_id']
    candidates=[]
    for c in d['candidates']:
        observations=c['observations'];pairs=c['verified_pairs'];files=c['source_versions'][0]['files']
        candidates.append({'candidate':c['candidate'],'source_path':c['path'],'files':files,'summary':c['summary'],'independent_confirmation':c['independent_confirmation_summary'],'by_run':c['by_run_summary'],'public_gate':'PASSED_EXACT_PAIR' if pairs else 'NOT_RUN','verified_pairs':pairs,'primary_time_delta_vs_actual_declared_parent_pct':[o['time_change_pct_vs_parent'] for o in observations if o['calibration']=='primary'],'independent_time_delta_vs_actual_parent_pct':[o['time_change_pct_vs_parent'] for o in observations if o['calibration']=='primary' and o['role']=='independent_confirmation' and o['entry_role']=='candidate'],'formal_submission_sent':False,'formal_reward_pool_share_pct':None})
        for version in c['source_versions']:
            p=ROOT/version['path']/'manifest.json'
            if p.exists() and p.parent.name.startswith('r22-'):
                m=read(p);assert m['hashes']==version['files'];m['performance_status']='ORIGINAL_PUBLIC_TIMING_AVAILABLE_SEE_R22_EVIDENCE';m['performance_evidence']='evidence/round22/final-analysis.json';m['formal_submission_sent']=False;write(p,m)
    result={'status':'FIXED_BUDGET_DELIVERY_FORMAL_10PCT_OBJECTIVE_NOT_ACHIEVED','generated_at_utc':datetime.now(timezone.utc).isoformat(),'budget':budget,'snapshot':d['snapshot'],'candidate_count':len(candidates),'candidates':candidates,'independent_10pct_counts':{c['candidate']:{k:v['at_least_10_count'] for k,v in c['independent_confirmation'].items()} for c in candidates},'public_gate_passed_pairs':sum(g['status']=='EXACT_ORIGINAL_PUBLIC_GATE_ACCEPTED' for g in audit['full_gates']),'best_all_original_protocol_conditional_share_pct':max((o['single_pool_share_pct'] for c in d['candidates'] for o in c['observations']),default=0),'analysis':a.analysis.resolve().relative_to(ROOT).as_posix(),'audit':a.audit.resolve().relative_to(ROOT).as_posix(),'formal_submission_sent':False,'formal_admission':'UNKNOWN','formal_payable_target':'NOT_ESTABLISHED','limits':['All pool percentages are conditional public transfers under the saved official snapshot, not formal rewards or success probabilities.','Full gates bind exact Rust/Lean and original verification only; native parity and reused proof do not confer acceptance on a different pair.','Discovery, independent confirmation, later same-source controls and diagnosis remain separate.','Fixed11 versus balanced20 diagnostic lacks same-repetition fixed20 control; no order-only causal claim.','No new official submission, registration, signatures or financial actions.']}
    combo=next(c for c in d['candidates'] if c['candidate']=='r22-595-chain-halfhead')
    potential={'status':'INFERRED_HIGH_POTENTIAL_NOT_VERIFIED_FINAL_CANDIDATE','candidate':combo['candidate'],'path':combo['path'],'files':combo['source_versions'][0]['files'],'snapshot':d['snapshot'],'observations':[{k:o[k] for k in ('run_id','block','calibration','projected_time','projected_size_pct','single_pool_share_pct','time_change_pct_vs_parent')} for o in combo['observations']],'full_gate':'NOT_RUN','new_independent_confirmation':'NOT_RUN','next_priority':'Run original fullgate on these exact bytes, then new independently confirmed original paired blocks; retain current0percent block and bothcontrols.','estimated_next_wall_minutes':[25,28],'estimate_basis':'Two observed original fullgates14to17minutes plus a new paired confirmation roughly11minutes, before any Leanrepair; confirmationrunners can be parallel.','proof_repair_cost':'UNKNOWN','formal_submission_sent':False,'scope':'One actualblock has bothprimary/shadow>=10percent, anotherblockbothzero. Not stabletarget achievement or formalreward. No latejob dispatched beyond fixedwindow.'}
    write(E/'highest-potential.json',potential)
    result['priority_unconfirmed_candidate']={k:potential[k] for k in ('candidate','files','full_gate','new_independent_confirmation','estimated_next_wall_minutes')}
    write(E/'final-summary.json',result)
    conclusions=collections.Counter(audit['run_conclusions'].values());gate_count=result['public_gate_passed_pairs']
    lines=['# 第二十二轮：追加一小时继续冲击10%竞赛池份额','','固定窗口：北京时间 **2026-10-11 00:37:07–01:37:07**。准备、排队、修复、实验、确认和报告计入这一小时；第21轮已结束，原起点未重置。执行规则见[AGENTS.md](../../AGENTS.md)。','','**正式10%目标未建立。** 本轮未上传竞赛。以下均为公共条件估算；高峰值与独立确认分列，不能凭两点中位数或平均坐标宣布达标。',f"最终官方快照 **{d['snapshot']['snapshot_id']}**，计算时间 `{d['snapshot']['computed_at']}`，freshness=`{d['snapshot'].get('freshness','UNKNOWN')}`。",'', '**VERIFIED**：原始计时、源码／证明哈希、原版编码输出、CI回执与两份完整公共gate。**INFERRED**：以正式595为锚的公共两轴迁移及评分重放。**UNKNOWN**：私有集、未来准入、正式可支付份额和模型可归因金额。','','## 候选与全部原协议观测','','全量包括后来同源码作为对照时的观测；冻结确认单独列于下一表。主／影子是同一计时块的两种校准视图，不计成两份独立样本。每个runner和逐文件总压缩时间、配对incumbent、工具链／库身份在[全量分析](../../evidence/round22/final-analysis.json)及原始JSONL。','','|候选|主中位／范围|主零次数／≥10次数|影子中位／范围|影子零次数／≥10次数|完整gate|','|---|---:|---:|---:|---:|---|']
    for c in candidates:
        p,s=c['summary']['primary'],c['summary']['shadow']
        lines.append(f"|[{c['candidate']}](../../{c['source_path']})|{dist(p)}|{p['zero_count']}/{p['n']} · {p['at_least_10_count']}/{p['n']}|{dist(s)}|{s['zero_count']}/{s['n']} · {s['at_least_10_count']}/{s['n']}|{c['public_gate']}|")
    lines+=['','达到门槛的样本次数不是正式成功概率。全部最佳值见JSON `best_pct`；各runner分别统计见 `by_run_summary`。平均坐标分数保留为 `score_at_center_NOT_expected_reward_pct`，不解释为期望奖励。','','## 冻结后的新独立确认','','|候选|新runner／块|主中位／范围；零；≥10|影子中位／范围；零；≥10|相对实际595时间范围|','|---|---:|---|---|---:|']
    for c in candidates:
        q=c['independent_confirmation']
        if not q:continue
        p,s=q['primary'],q['shadow'];delta=c['independent_time_delta_vs_actual_parent_pct']
        lines.append(f"|{c['candidate']}|{p['runner_count']}／{p['n']}|{dist(p)}；{p['zero_count']}/{p['n']}；{p['at_least_10_count']}/{p['n']}|{dist(s)}；{s['zero_count']}/{s['n']}；{s['at_least_10_count']}/{s['n']}|{min(delta):+.6f}%至{max(delta):+.6f}%|")
    lines+=['','速度变化负号表示更快。确认启动前已有完整gate，精确Rust／Lean冻结后未改；发现期与后来的控制块不混入确认队列。独立确认存在失效时保留，不用峰值替代。','','## 机制与决策','','- 刚公开的595作为实际新起点：保留原作者、来源和哈希；通过普通公开API取得，不绕过源代码权限。先检查其只有一条辅助环，不能照搬539的双环假设。','- `prev16`缩小前驱表示，`halfhead`只缩小一个主表，`prev16-word8`组合字级比较。28文件保持595精确token／输出；首次主视图出现约23.64%、23.38%、15.46%的单块峰值，另一块均0；改用同源码影子对照后全0。','- 原协议控制出现正负约0.33%的分歧，足以改变≥10%的判断。先低成本重放，再安排同源码诊断和独立确认，未将峰值称作成功，也未仅因某块较慢淘汰。','- `row6-chain`在原本只试表头的一条路线追加一个旧匹配：实际总输出少7238B，仅lean.txt改变；首次两块比实际595快0.008%和0.090%，但两种校准下均0份额。它通过精确完整gate，作为有依据的质量起点保留。','- 全PC取消向后折叠多161484B，平均文件压缩率恶化约0.766个百分点，首次两块总计时慢约1.56%，停止扩展该实现；这不排除其他局部折叠策略。','- 最后只组合已经测量的缩表和单步旧匹配。新源在28文件与实际chain父版本token／编码字节相同；速度必须重新测，不能相加组件增益。这个组合尚未跑完整gate或冻结后的新独立确认。','', '早期准备脚本先漏了续跑模板，再漏接已有候选列表。首批A实际是基线-only；保留回执，修正B入口并添加候选数量断言。没有把基线输出标成优化收益。细节见[准备记录](../../evidence/round22/preparation-notes.json)。','','## 测量可信度与评分敏感性','','起始快照595大小的≥10%速度区间约为父版本提速0.32%–0.75%，网格宽约0.43%；实际chain质量收益未明显拓宽该窗口。这是合成评分几何，非实际测量、误差界或成功概率；当前快照的结果以全量重放为准。见[空间重放](../../evidence/round22/quality-space.json)。','', '同源码分歧包括候选计时与配对分母变化。将实际逐文件incumbent保持为同一参考的诊断重组显示两个因素都会影响坐标；不把该重组当作新官方协议。见[C分解](../../evidence/round22/control-c-decomposition.json)与[E分解](../../evidence/round22/control-e-decomposition.json)。','','独立的多方法诊断使用显式CPU：两对源码／共享库身份一致，编码、token和输入身份复核。它与原版单候选配对协议分列，不参与上述份额样本。','','|诊断协议|块|595副本差异|候选副本差异|候选对两份595的速度范围|','|---|---:|---:|---:|---:|']
    for r in diagnostic['blocks']:
        lo,hi=r['candidate_vs_all_parent_aliases_range_pct'];lines.append(f"|{r['protocol']}|{r['block']}|{r['parent_alias_gap_pct']:+.6f}%|{r['candidate_alias_gap_pct']:+.6f}%|{lo:+.6f}%至{hi:+.6f}%|")
    lines+=['','此次fixed11与balanced20同时改变顺序和重复次数，**缺少同次数fixed20对照**，不能归因于单一顺序效应。后续准备器已恢复fixed11／fixed20／balanced20三组；已冻结F回执保持原样，未重写为三组。见[诊断审计](../../evidence/round22/diagnostic-analysis.json)。','','## 精确验收与审阅包','','|对象|Rust SHA-256|Lean SHA-256|原版gate|','|---|---|---|---|']
    for name,files in audit['candidate_pairs'].items():
        accepted=[g for g in audit['full_gates'] if g['candidate']==name]
        lines.append(f"|{name}|`{files['parse.rs']}`|`{files['Parse.lean']}`|{accepted[0]['status'] if accepted else 'NOT_RUN'}|")
    lines+=['',f'共{gate_count}份精确文件对通过官方重新提取、原始LZ77.Obligation、公理白名单与公共roundtrip。半表gate444.1s，单步旧匹配gate539.1s；原版Lean900s限制保留。冒烟计时不计成性能块。', '', '[两个精确双文件审阅ZIP及哈希](../../evidence/round22/delivery/receipt.json)已准备；仅为本地审阅包，没有正式上传、签名或正式submission digest。新组合复用相同Lean文本也不继承另一个Rust的验收。','','## 单独、联合和竞争影响','','每个候选单独加入时的主／影子分布如上；同run／同block的两者联合见全量分析 `joint`，完整同块组合及原Top1影响见[影响重放](../../evidence/round22/final-impact.json)。联合分数重新构建前沿并归一化，不相加。不同runner没有捏造配对联合数据；未来身份、同hotkey最旧存活规则、额度及准入仍另行核验。','', '例如首次C块1中，prev16与halfhead单独约23.64%／23.38%，同块联合由prev16支配halfhead，后者0；影子视图两者都0。这说明两个峰值不能相加，也不构成两个稳定候选。','','## 实际消耗与下一步','',f"共{audit['dispatched_runs']}个手动作业，结论 `{dict(conclusions)}`；{audit['original_paired_processes']}个原协议配对进程（含对照），{audit['distinct_candidate_rust_count']}份不同新Rust。原始artifact {audit['raw_file_count']}文件／{audit['raw_bytes']:,}字节均通过SHA-256，见[审计](../../evidence/round22/audit-final.json)。runner累计{audit['runner_minutes']:.2f}分钟是并发作业之和，不是研究墙钟时间或金额。",'', '账户真实观察与时间见[用量记录](../../evidence/round22/usage-summary.json)；0次重置、0次购买。GitHub实际计费和模型可归因金额UNKNOWN。', '', '最高价值后续：以已验证的单步旧匹配及其缩表组合为起点，只推进有真实速度／质量余量的变化；先补等重复次数顺序对照并区分配对分母，避免再次用噪声进入窄窗。若组合有价值，先为其精确Rust重新完整gate，再做新的冻结确认；若机会仍窄，转向能明显改善质量的不同机制或新合法公开起点，不通过无价值延时调分。','', '[提交看板](../../DASHBOARD.md)已按当前官方快照刷新；初始份额保留原记录，累计α为API记录，非钱包到账或净收益。源码／证明、所有负结果和原始回执在研究分支保留。','']
    lines+=['## CI阶段边界与高峰复核成本','','最后K因12分钟上限显示cancelled；完整两块、16个原协议配对进程已保存，零失败，state到gate阶段。只能确认这段计时数据完整，不能称整体CI成功或新组合完整gate通过。A仍是基线-only。','','优先保留组合：K块2单独主校准16.666385%、影子16.353782%，块1两者0；主中位8.333193%、影子8.176891%。它比该块实际chain父版本只快0.040089%，不能将微小跨界解释为稳定收益。新组合完整gate与独立确认NOT_RUN，精确文件、坐标和下一步见[高潜力交接](../../evidence/round22/highest-potential.json)。同块与已验收halfhead或chain联合时保留这一块的组合份额，另一者0；没有相加。','','prev16保留当前快照约23.59%的单块主校准收益空间，同时记录另一块0和同源码校准全0。其Lean仍为未验收草稿；不能仅凭峰值进入正式包。以本轮两次实际完整gate约14–17分钟加新的runner确认约11分钟估算，下一次完整复核至少需要约25–28分钟墙钟预算，证明修复时间UNKNOWN；这是资源估计，不是成功概率。','','收尾时曾按collector的平均坐标误述组合全0，逐块重放后已更正。未来先读每块、每个参照的分布，再写结论；平均坐标的on_frontier字段不能替代逐块奖励分数。','']
    lines.insert(7,'当前优先保留未确认的`r22-595-chain-halfhead`：同一块在两份595参照下分别约16.67%／16.35%，另一块均0。还未通过新精确完整gate或新的独立确认，不能宣布稳定达标。\n')
    (ROOT/'docs/rounds/round22.md').write_bytes(('\n'.join(lines)).encode())
    index=ROOT/'docs/TASK_INDEX.md';text=index.read_text();row=f"| round22 | [第二十二轮：追加一小时](rounds/round22.md) | {audit['dispatched_runs']}作业／{audit['distinct_candidate_rust_count']}份新Rust；两份完整公共gate，独立确认与对照诊断分列；未建立正式10%目标，无正式上传。 |\n"
    if '| round22 |' not in text:text=text.replace('| maintenance-20261008 |',row+'| maintenance-20261008 |');index.write_bytes(text.encode())
    tasks=read(ROOT/'docs/tasks.json');tasks['updated_on']='2026-10-11'
    entry={'id':'round22','title':'追加一小时继续冲击10%','tags':['595','halfhead','chain','计时顺序','归一化','10%','独立确认','完整gate'],'report':'docs/rounds/round22.md','evidence':['evidence/round22'],'decision':'六份新Rust，两份完整公共gate；高峰与零份额、冻结确认和诊断分列；无正式上传，10%正式目标未建立。'}
    tasks['tasks']=[t for t in tasks['tasks'] if t['id']!='round22']+[entry];write(ROOT/'docs/tasks.json',tasks)
    print(json.dumps({'report':'docs/rounds/round22.md','candidates':len(candidates),'best_conditional_pct':result['best_all_original_protocol_conditional_share_pct'],'gate_pairs':gate_count,'independent_10pct_counts':result['independent_10pct_counts']},indent=2))

if __name__=='__main__':main()
